-- we don't know how to generate schema CANVAS_DATA_NIGHTLY_IMPORTS (class Schema) :(
create or replace table ASSIGNMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	TITLE VARCHAR(256) UTF8,
	DESCRIPTION VARCHAR(500000) UTF8,
	DUE_AT TIMESTAMP,
	UNLOCK_AT TIMESTAMP,
	LOCK_AT TIMESTAMP,
	POINTS_POSSIBLE DECIMAL(18,3),
	GRADING_TYPE VARCHAR(256) UTF8,
	SUBMISSION_TYPES VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PEER_REVIEW_COUNT DECIMAL(18),
	PEER_REVIEWS_DUE_AT TIMESTAMP,
	PEER_REVIEWS_ASSIGNED BOOLEAN,
	PEER_REVIEWS BOOLEAN,
	AUTOMATIC_PEER_REVIEWS BOOLEAN,
	ALL_DAY BOOLEAN,
	ALL_DAY_DATE DATE,
	COULD_BE_LOCKED BOOLEAN,
	GRADE_GROUP_STUDENTS_INDIVIDUALLY BOOLEAN,
	ANONYMOUS_PEER_REVIEWS BOOLEAN,
	MUTED BOOLEAN,
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	FIELD_POSITION DECIMAL(18),
	VISIBILITY VARCHAR(256) UTF8,
	EXTERNAL_TOOL_ID DECIMAL(18)
)
/

create or replace table SUBMISSION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	BODY VARCHAR(500000) UTF8,
	URL VARCHAR(256) UTF8,
	GRADE VARCHAR(256) UTF8,
	SUBMITTED_AT TIMESTAMP,
	SUBMISSION_TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PROCESSED BOOLEAN,
	PROCESS_ATTEMPTS DECIMAL(18),
	GRADE_MATCHES_CURRENT_SUBMISSION BOOLEAN,
	PUBLISHED_GRADE VARCHAR(256) UTF8,
	GRADED_AT TIMESTAMP,
	HAS_RUBRIC_ASSESSMENT BOOLEAN,
	ATTEMPT DECIMAL(18),
	HAS_ADMIN_COMMENT BOOLEAN,
	ASSIGNMENT_ID DECIMAL(18),
	EXCUSED VARCHAR(256) UTF8,
	GRADED_ANONYMOUSLY VARCHAR(256) UTF8,
	GRADER_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GRADE_STATE VARCHAR(256) UTF8
)
/

create or replace table SUBMISSION_FACT
(
	SUBMISSION_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GRADER_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	SCORE DECIMAL(18,3),
	PUBLISHED_SCORE DECIMAL(18,3),
	WHAT_IF_SCORE DECIMAL(18,3),
	SUBMISSION_COMMENTS_COUNT DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table ASSIGNMENT_GROUP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DEFAULT_ASSIGNMENT_NAME VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table USER_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	TIME_ZONE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	VISIBILITY VARCHAR(256) UTF8,
	SCHOOL_NAME VARCHAR(256) UTF8,
	SCHOOL_FIELD_POSITION VARCHAR(256) UTF8,
	GENDER VARCHAR(256) UTF8,
	LOCALE VARCHAR(256) UTF8,
	PUBLIC VARCHAR(256) UTF8,
	BIRTHFIELD_DATE TIMESTAMP,
	COUNTRY_CODE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	SORTABLE_NAME VARCHAR(256) UTF8,
	GLOBAL_CANVAS_ID VARCHAR(256) UTF8
)
/

create or replace table DISCUSSION_TOPIC_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	TITLE VARCHAR(65535) UTF8 default NULL,
	MESSAGE VARCHAR(500000) UTF8,
	TYPE VARCHAR(65535) UTF8 default NULL,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	LAST_REPLY_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELAYED_POST_AT TIMESTAMP,
	POSTED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	DISCUSSION_TYPE VARCHAR(65535) UTF8 default NULL,
	PINNED BOOLEAN,
	LOCKED BOOLEAN,
	COURSE_ID DECIMAL(18),
	GROUP_ID DECIMAL(18)
)
/

create or replace table DISCUSSION_TOPIC_FACT
(
	DISCUSSION_TOPIC_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_LENGTH DECIMAL(18),
	GROUP_ID DECIMAL(18),
	GROUP_PARENT_COURSE_ID DECIMAL(18),
	GROUP_PARENT_ACCOUNT_ID DECIMAL(18),
	GROUP_PARENT_COURSE_ACCOUNT_ID DECIMAL(18)
)
/

create or replace table COURSE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	CODE VARCHAR(256) UTF8,
	TYPE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	START_AT TIMESTAMP,
	CONCLUDE_AT TIMESTAMP,
	PUBLICLY_VISIBLE BOOLEAN,
	SIS_SOURCE_ID VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	WIKI_ID DECIMAL(18),
	SYLLABUS_BODY VARCHAR(500000) UTF8
)
/

create or replace table DISCUSSION_ENTRY_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	MESSAGE VARCHAR(500000) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	DEPTH DECIMAL(18)
)
/

create or replace table DISCUSSION_ENTRY_FACT
(
	DISCUSSION_ENTRY_ID DECIMAL(18),
	PARENT_DISCUSSION_ENTRY_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	TOPIC_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	TOPIC_USER_ID DECIMAL(18),
	TOPIC_ASSIGNMENT_ID DECIMAL(18),
	TOPIC_EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_LENGTH DECIMAL(18)
)
/

create or replace table ENROLLMENT_TERM_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DATE_START TIMESTAMP,
	DATE_END TIMESTAMP,
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table CONVERSATION_MESSAGE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	FIELD_GENERATED BOOLEAN,
	HAS_ATTACHMENTS BOOLEAN,
	HAS_MEDIA_OBJECTS BOOLEAN,
	BODY VARCHAR(500000) UTF8
)
/

create or replace table CONVERSATION_MESSAGE_PARTICIPANT_FACT
(
	CONVERSATION_MESSAGE_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_SIZE_BYTES DECIMAL(18),
	MESSAGE_CHARACTER_COUNT DECIMAL(18),
	MESSAGE_WORD_COUNT DECIMAL(18),
	MESSAGE_LINE_COUNT DECIMAL(18)
)
/

create or replace table COURSE_SCORE_FACT
(
	SCORE_ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	CURRENT_SCORE DECIMAL(18,3),
	FINAL_SCORE DECIMAL(18,3),
	MUTED_CURRENT_SCORE DECIMAL(18,3),
	MUTED_FINAL_SCORE DECIMAL(18,3)
)
/

create or replace table ENROLLMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	ROLE_ID DECIMAL(18),
	TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	START_AT TIMESTAMP,
	END_AT TIMESTAMP,
	COMPLETED_AT TIMESTAMP,
	SELF_ENROLLED BOOLEAN,
	SIS_SOURCE_ID VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	LAST_ACTIVITY_AT TIMESTAMP
)
/

create or replace table ENROLLMENT_FACT
(
	ENROLLMENT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	COMPUTED_FINAL_SCORE DECIMAL(18,3),
	COMPUTED_CURRENT_SCORE DECIMAL(18,3)
)
/

create or replace table PSEUDONYM_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	LAST_REQUEST_AT TIMESTAMP,
	LAST_LOGIN_AT TIMESTAMP,
	CURRENT_LOGIN_AT TIMESTAMP,
	LAST_LOGIN_IP VARCHAR(256) UTF8,
	CURRENT_LOGIN_IP VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PASSWORD_AUTO_FIELD_GENERATED BOOLEAN,
	DELETED_AT TIMESTAMP,
	SIS_USER_ID VARCHAR(256) UTF8,
	UNIQUE_NAME VARCHAR(256) UTF8,
	INTEGRATION_ID VARCHAR(256) UTF8,
	AUTHENTICATION_PROVIDER_ID DECIMAL(18)
)
/

create or replace table ACCOUNT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DEPTH DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	PARENT_ACCOUNT VARCHAR(256) UTF8,
	PARENT_ACCOUNT_ID DECIMAL(18),
	GRANDPARENT_ACCOUNT VARCHAR(256) UTF8,
	GRANDPARENT_ACCOUNT_ID DECIMAL(18),
	ROOT_ACCOUNT VARCHAR(256) UTF8,
	ROOT_ACCOUNT_ID DECIMAL(18),
	SUBACCOUNT1 VARCHAR(256) UTF8,
	SUBACCOUNT1_ID DECIMAL(18),
	SUBACCOUNT2 VARCHAR(256) UTF8,
	SUBACCOUNT2_ID DECIMAL(18),
	SUBACCOUNT3 VARCHAR(256) UTF8,
	SUBACCOUNT3_ID DECIMAL(18),
	SUBACCOUNT4 VARCHAR(256) UTF8,
	SUBACCOUNT4_ID DECIMAL(18),
	SUBACCOUNT5 VARCHAR(256) UTF8,
	SUBACCOUNT5_ID DECIMAL(18),
	SUBACCOUNT6 VARCHAR(256) UTF8,
	SUBACCOUNT6_ID DECIMAL(18),
	SUBACCOUNT7 VARCHAR(256) UTF8,
	SUBACCOUNT7_ID DECIMAL(18),
	SUBACCOUNT8 VARCHAR(256) UTF8,
	SUBACCOUNT8_ID DECIMAL(18),
	SUBACCOUNT9 VARCHAR(256) UTF8,
	SUBACCOUNT9_ID DECIMAL(18),
	SUBACCOUNT10 VARCHAR(256) UTF8,
	SUBACCOUNT10_ID DECIMAL(18),
	SUBACCOUNT11 VARCHAR(256) UTF8,
	SUBACCOUNT11_ID DECIMAL(18),
	SUBACCOUNT12 VARCHAR(256) UTF8,
	SUBACCOUNT12_ID DECIMAL(18),
	SUBACCOUNT13 VARCHAR(256) UTF8,
	SUBACCOUNT13_ID DECIMAL(18),
	SUBACCOUNT14 VARCHAR(256) UTF8,
	SUBACCOUNT14_ID DECIMAL(18),
	SUBACCOUNT15 VARCHAR(256) UTF8,
	SUBACCOUNT15_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table COURSE_SECTION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	DEFAULT_SECTION BOOLEAN,
	ACCEPTING_ENROLLMENTS BOOLEAN,
	CAN_MANUALLY_ENROLL BOOLEAN,
	START_AT TIMESTAMP,
	END_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	RESTRICT_ENROLLMENTS_TO_SECTION_DATES BOOLEAN,
	NONXLIST_COURSE_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table ERROR_TABLE
(
	ROW_NR DECIMAL(18),
	ERROR_TEXT VARCHAR(1000) UTF8,
	TAG VARCHAR(1000) UTF8,
	TRUNCATED BOOLEAN,
	CSV_DATA VARCHAR(2000000) UTF8
)
/

create or replace table CU_CANVAS_COURSE_DISCUSSIONS_METRICS
(
	DISCUSSION_TOPIC_ID DECIMAL(18),
	DISCUSSION_TOPIC_EDITOR_ID DECIMAL(18),
	DISCUSSION_TOPIC_EDITOR_NAME VARCHAR(256) UTF8,
	DISCUSSION_TOPIC_TITLE VARCHAR(256) UTF8,
	DISCUSSION_TOPIC_TYPE VARCHAR(256) UTF8,
	DISCUSSION_TOPIC_WORD_COUNT DECIMAL(18),
	DISCUSSION_TOPIC_MEDIA_TYPE VARCHAR(100) UTF8,
	DISCUSSION_TOPIC_CREADTED_AT TIMESTAMP,
	TERM_NAME VARCHAR(256) UTF8,
	SIS_TERM_NAME VARCHAR(256) UTF8,
	COURSE_NAME VARCHAR(256) UTF8,
	CANVAS_COURSE_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(100) UTF8,
	SCHOOL_COLLEGE VARCHAR(100) UTF8,
	CANVAS_RESPONSE_USER_ID DECIMAL(18),
	CANVAS_RESPONSE_USER_NAME VARCHAR(256) UTF8,
	RESPONSE_MESSAGE_ID DECIMAL(18),
	RESPONSE_PARENT_MESSAGE_ID DECIMAL(18),
	RESPONSE_MESSAGE_WORD_COUNT DECIMAL(18),
	RESPONSE_MEDIA_TYPE VARCHAR(100) UTF8,
	RESPONSE_MESSAGE_CREATED_AT TIMESTAMP,
	ENROLLMENT_ID DECIMAL(18)
)
/

create or replace table CU_CANVAS_TERM_LOOKUP
(
	CANVAS_CURRENT_TERM_ID DECIMAL(18),
	CANVAS_CURRENT_TERM_NAME VARCHAR(100) UTF8,
	CANVAS_PREVIOUS_TERM_ID DECIMAL(18),
	CANVAS_PREVIOUS_TERM_NAME VARCHAR(100) UTF8,
	CANVAS_NEXT_TERM_ID DECIMAL(18),
	CANVAS_NEXT_TERM_NAME VARCHAR(100) UTF8
)
/

create or replace table CANVAS_COURSE_TEACHER_MESSAGES_VIEW
(
	ENROLLMENT_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	CONVERSATION_MESSAGE_ID DECIMAL(18),
	CANVAS_USER_ID DECIMAL(18),
	USER_NAME VARCHAR(256) UTF8,
	USER_SORTABLE_NAME VARCHAR(256) UTF8,
	ENROLLMENT_TYPE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	TERM_NAME VARCHAR(256) UTF8,
	SIS_TERM VARCHAR(256) UTF8,
	COURSE_NAME VARCHAR(256) UTF8,
	CANVAS_COURSE_ID DECIMAL(18),
	SIS_SECTION_ID VARCHAR(256) UTF8,
	COURSE_CODE VARCHAR(256) UTF8,
	SCHOOL_COLLEGE VARCHAR(256) UTF8
)
/

create or replace table GROUP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DESCRIPTION VARCHAR(500000) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	IS_PUBLIC BOOLEAN,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CONTEXT_TYPE VARCHAR(256) UTF8,
	CATEGORY VARCHAR(500000) UTF8,
	JOIN_LEVEL VARCHAR(256) UTF8,
	DEFAULT_VIEW VARCHAR(256) UTF8,
	SIS_SOURCE_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table GROUP_MEMBERSHIP_FACT
(
	GROUP_ID DECIMAL(18),
	PARENT_COURSE_ID DECIMAL(18),
	PARENT_ACCOUNT_ID DECIMAL(18),
	PARENT_COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GROUP_MEMBERSHIP_ID VARCHAR(256) UTF8
)
/

create or replace table GROUP_MEMBERSHIP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	MODERATOR VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table SUBMISSION_COMMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	RECIPIENT_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	ASSESSMENT_REQUEST_ID DECIMAL(18),
	GROUP_COMMENT_ID VARCHAR(65535) UTF8,
	COMMENT VARCHAR(65535) UTF8,
	AUTHOR_NAME VARCHAR(65535) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	ANONYMOUS BOOLEAN,
	TEACHER_ONLY_COMMENT BOOLEAN,
	HIDDEN BOOLEAN,
	distribute by SUBMISSION_ID
)
/

create or replace table SUBMISSION_COMMENT_FACT
(
	SUBMISSION_COMMENT_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	RECIPIENT_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	MESSAGE_SIZE_BYTES DECIMAL(18),
	MESSAGE_CHARACTER_COUNT DECIMAL(18),
	MESSAGE_WORD_COUNT DECIMAL(18),
	MESSAGE_LINE_COUNT DECIMAL(18),
	distribute by COURSE_ID
)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_STUDENT_ENROLLMENTS_BY_COURSE_VIEW as
  (

    select
      CANVAS_COURSE_ID,
      CANVAS_COURSE_UI_ID,
      COURSE_NAME,
      COURSE_SECTION_NAME,
      CANVAS_SECTION_ID,
      SIS_SECTION_ID,
      TERM_NAME,
      SIS_TERM,
      count(1) as STUDENT_ENROLLMENT_COUNT
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW
    where ENROLLMENT_TYPE = 'Student'
          and ENROLLMENT_STATE = 'active'
    group by
      CANVAS_COURSE_ID,
      CANVAS_COURSE_UI_ID,
      COURSE_NAME,
      COURSE_SECTION_NAME,
      CANVAS_SECTION_ID,
      SIS_SECTION_ID,
      TERM_NAME,
      SIS_TERM
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSION_TOPIC_ROLLUP_VIEW as
  (
    select
      cdv.CANVAS_COURSE_ID,
      count(distinct cdv.DISCUSSION_TOPIC_ID)             as DISCUSSION_AND_ANNOUNCEMENT_COUNT,
      max(days_between(now(), cdv.DISCUSSION_CREATED_AT)) as DAYS_SINCE_LAST_DISCUSSION
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_VIEW cdv
    group by
      cdv.CANVAS_COURSE_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_RESPONSE_ROLLUP_VIEW as
  (
    select
      cev.CANVAS_COURSE_ID,
      cev.CANVAS_USER_ID,
      cev.ENROLLMENT_ID,
      count(distinct cdv.DISCUSSION_ENTRY_ID)                      as DISCUSSION_REPLIES,
      max(days_between(now(), cdv.DISCUSSION_RESPONSE_CREATED_AT)) as DAYS_SINCE_LAST_DISCUSSION_RESPONSE
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_VIEW cdv
      join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
        on cdv.ENROLLMENT_ROLLUP_ID = cev.ENROLLMENT_ID
    group by
      cev.CANVAS_COURSE_ID,
      cev.CANVAS_USER_ID,
      cev.ENROLLMENT_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_UNGRADED_ASSIGNMENTS_ROLLUP_VIEW as
  (
    select
      ua.COURSE_ID,
      count(1)                               as UNGRADED_ASSIGNMENT_COUNT,
      MEDIAN(ua.GRADE_DAYS_SINCE_SUBMISSION) as MEDIAN_DAYS_SINCE_UNGRADED_SUBIMSSION,
      MAX(ua.GRADE_DAYS_SINCE_SUBMISSION)    as MAX_DAYS_SINCE_UNGRADED_SUBMISSION
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_UNGRADED_ASSIGNMENTS_VIEW ua
    group by
      ua.COURSE_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_MESSAGES_VIEW as
  (
    select distinct

      cev.ENROLLMENT_ID,
      cmd.CONVERSATION_ID,
      cmpf.CONVERSATION_MESSAGE_ID,
      cev.CANVAS_USER_ID,
      cev.USER_NAME,
      cev.USER_SORTABLE_NAME,
      cev.ENROLLMENT_TYPE,
      convert_tz(cmd.CREATED_AT, 'UTC', 'US/MOUNTAIN') as CREATED_AT,
      cev.TERM_NAME,
      cev.SIS_TERM,
      cev.COURSE_NAME,
      cev.CANVAS_COURSE_ID,
      cev.SIS_SECTION_ID,
      cev.COURSE_CODE,
      cev.SCHOOL_COLLEGE
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CONVERSATION_MESSAGE_DIM cmd
      join CANVAS_DATA_NIGHTLY_IMPORTS.CONVERSATION_MESSAGE_PARTICIPANT_FACT cmpf
        on cmd.ID = cmpf.CONVERSATION_MESSAGE_ID and cmd.AUTHOR_ID = cmpf.USER_ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
        on cev.ENROLLMENT_ID = cmpf.ENROLLMENT_ROLLUP_ID



  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_UNGRADED_ASSIGNMENTS_VIEW as
  (
    select
      av.*,
      case
        when av.DUE_AT is not null and av.DUE_AT >= av.SUBMITTED_AT
        then days_between(now(), av.DUE_AT)
        else days_between(now(), av.SUBMITTED_AT)
      end as GRADE_DAYS_SINCE_SUBMISSION
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ASSIGNMENTS_VIEW av
    where
      av.SCORE is null
      and (av.DUE_AT <= now() or av.DUE_AT is null)
      and av.SUBMITTED_AT is not null

  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_INSTRUCTOR_METRICS_VIEW as
  (
    select distinct
      cev.USER_NAME,
      cev.CANVAS_USER_ID,
      cev.CANVAS_USER_UI_ID,
      cev.ENROLLMENT_TYPE,
      cev.COURSE_NAME,
      cev.CANVAS_COURSE_ID,
      cev.CANVAS_COURSE_UI_ID,
      cev.COURSE_SECTION_NAME,
      cev.CANVAS_SECTION_ID,
      cev.TERM_NAME,
      cev.SIS_TERM,
      cev.SCHOOL_COLLEGE,
      cev.INSTRUCTION_MODE,
      sev.STUDENT_ENROLLMENT_COUNT,
      cev.LAST_ACTIVITY_IN_COURSE,
      days_between(now(),cev.LAST_ACTIVITY_IN_COURSE) as DAYS_SINCE_LAST_COURSE_ACTIVITY,
      uav.UNGRADED_ASSIGNMENT_COUNT,
      uav.MEDIAN_DAYS_SINCE_UNGRADED_SUBIMSSION,
      uav.MAX_DAYS_SINCE_UNGRADED_SUBMISSION,
      dtv.DISCUSSION_AND_ANNOUNCEMENT_COUNT,
      dtv.DAYS_SINCE_LAST_DISCUSSION,
      drv.DISCUSSION_REPLIES,
      drv.DAYS_SINCE_LAST_DISCUSSION_RESPONSE
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
      join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_STUDENT_ENROLLMENTS_BY_COURSE_VIEW sev
        on cev.CANVAS_COURSE_ID = sev.CANVAS_COURSE_ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_UNGRADED_ASSIGNMENTS_ROLLUP_VIEW uav
        on cev.CANVAS_COURSE_ID = uav.COURSE_ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_RESPONSE_ROLLUP_VIEW drv
        on cev.ENROLLMENT_ID = drv.ENROLLMENT_ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSION_TOPIC_ROLLUP_VIEW dtv
        on cev.CANVAS_COURSE_ID = dtv.CANVAS_COURSE_ID

    where
      (cev.ENROLLMENT_TYPE in ('Teacher', 'Ta'))
      and cev.ENROLLMENT_STATE = 'active'


  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW as
  (

    select
      distinct
      e.ENROLLMENT_ID,
      u.ID                                 as CANVAS_USER_ID,
      u.CANVAS_ID                          as CANVAS_USER_UI_ID ,
      trim(u.NAME)                         as USER_NAME,
      u.SORTABLE_NAME                      as USER_SORTABLE_NAME,
      REPLACE(ed."TYPE", 'Enrollment', '') as ENROLLMENT_TYPE,
      ed.WORKFLOW_STATE                    as ENROLLMENT_STATE,
      convert_tz(ed.CREATED_AT, 'UTC', 'US/MOUNTAIN') as ENROLLMENT_CREATED_AT,
      convert_tz(ed.UPDATED_AT , 'UTC', 'US/MOUNTAIN') as ENROLLMENT_UPDATED_AT,
      c.ID                                 as CANVAS_COURSE_ID,
      c.CANVAS_ID                          as CANVAS_COURSE_UI_ID,
      c.NAME                               as COURSE_NAME,
      c.CODE                               as COURSE_CODE,
      csd.id                               as CANVAS_SECTION_ID,
      csd.NAME                             as COURSE_SECTION_NAME,
      case
        when LEFT(RIGHT(csd.NAME,3),1) in ('H', 'h') THEN 'Hybrid'
        when LEFT(RIGHT(csd.NAME,3),1) in ('E', 'e') THEN 'Online'
        else 'In-Person'
      end as INSTRUCTION_MODE,
      csd.SIS_SOURCE_ID                    as SIS_SECTION_ID,
      c.START_AT                           as COURSE_START,
      c.CONCLUDE_AT                        as COURSE_END,
      c.SIS_SOURCE_ID                      as SIS_COURSE_ID,
      t.NAME                               as TERM_NAME,
      t.SIS_SOURCE_ID                      as SIS_TERM,
      a.SUBACCOUNT1                        as SCHOOL_COLLEGE,
      convert_tz(ed.LAST_ACTIVITY_AT , 'UTC', 'US/MOUNTAIN')  as LAST_ACTIVITY_IN_COURSE
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.ENROLLMENT_FACT e
      join CANVAS_DATA_NIGHTLY_IMPORTS.ENROLLMENT_DIM ed
        on e.ENROLLMENT_ID = ed.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.USER_DIM u
        on e.USER_ID = u.ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.PSEUDONYM_DIM p
        on u.id = p.USER_ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.COURSE_DIM c
        on e.COURSE_ID = c.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.ENROLLMENT_TERM_DIM t
        on c.ENROLLMENT_TERM_ID = t.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.ACCOUNT_DIM a
        on c.ACCOUNT_ID = a.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.COURSE_SECTION_DIM csd
        on csd.ID = ed.COURSE_SECTION_ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.PSEUDONYM_DIM pd
        on ed.USER_ID = pd.USER_ID
    where
      ed.WORKFLOW_STATE not in ('rejected', 'deleted')
      and csd.WORKFLOW_STATE not in ('rejected', 'deleted')
      and c.WORKFLOW_STATE not in ('rejected', 'deleted')
      and c.SIS_SOURCE_ID is not null
      and pd.WORKFLOW_STATE = 'active'
      and local.ENROLLMENT_TYPE not in ('StudentView', 'TeacherView', 'TaView', 'Observer', 'Designer')



  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW as
  (

    select
      cev.TERM_NAME,
      cev.CANVAS_USER_ID,
      cev.CANVAS_USER_UI_ID,
      cev.USER_NAME,
      cev.USER_SORTABLE_NAME,
      cev.ENROLLMENT_ID,
      cev.CANVAS_COURSE_ID,
      cev.CANVAS_SECTION_ID,
      cev.COURSE_SECTION_NAME,
      cev.COURSE_NAME,
      cev.COURSE_CODE,
      cev.INSTRUCTION_MODE,
      cev.ENROLLMENT_TYPE,
      cev.SCHOOL_COLLEGE,
      cav.ASSIGNMENT_ID,
      cav.ASSIGNMENT_GROUP,
      cav.ASSIGNMENT_TITLE,
      cav.ID as SUBMISSION_ID,
      cav.SCORE,
      cav.POINTS_POSSIBLE,
      cav.DUE_AT,
      cav.SUBMITTED_AT
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ASSIGNMENTS_VIEW cav
      join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
        on cev.ENROLLMENT_ID = cav.ENROLLMENT_ROLLUP_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_NAVIGATORS_ROLLUP_VIEW as
(
  select
    rsv.*,
    rcv.COURSE_ENROLLMENT_COUNT,
    rcv.COURSE_AVG_SCORE,
    rcv.COURSE_MIN_SCORE,
    rcv.COURSE_MAX_SCORE,
    rcv.COURSE_AVG_TIMELY_SUBMISSION_COUNT,
    rcv.COURSE_MIN_TIMELY_SUBMISSION_COUNT,
    rcv.COURSE_MAX_TIMELY_SUBMISSION_COUNT,
    rcv.COURSE_AVG_LATE_SUBMISSION_COUNT,
    rcv.COURSE_MIN_LATE_SUBMISSION_COUNT,
    rcv.COURSE_MAX_LATE_SUBMISSION_COUNT,
    rcv.COURSE_AVG_NO_SUBMISSION_COUNT,
    rcv.COURSE_MIN_NO_SUBMISSION_COUNT,
    rcv.COURSE_MAX_NO_SUBMISSION_COUNT
  from
    CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_ROLLUP_BY_STUDENT_VIEW rsv
    join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_ROLLUP_BY_COURSE_VIEW rcv
      on rsv.CANVAS_SECTION_ID = rcv.CANVAS_SECTION_ID
      and rsv.ASSIGNMENT_GROUP = rcv.ASSIGNMENT_GROUP
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_ROLLUP_BY_COURSE_VIEW as
(
select
  rsv.CANVAS_COURSE_ID,
  rsv.CANVAS_SECTION_ID,
  rsv.ASSIGNMENT_GROUP,
  COUNT(DISTINCT ENROLLMENT_ID) as COURSE_ENROLLMENT_COUNT,
  avg(rsv.SCORE) as COURSE_AVG_SCORE,
  min(rsv.SCORE) as COURSE_MIN_SCORE,
  max(rsv.SCORE) as COURSE_MAX_SCORE,
  avg(rsv.TIMELY_SUBMISSION_COUNT) as COURSE_AVG_TIMELY_SUBMISSION_COUNT,
  min(rsv.TIMELY_SUBMISSION_COUNT) as COURSE_MIN_TIMELY_SUBMISSION_COUNT,
  max(rsv.TIMELY_SUBMISSION_COUNT) as COURSE_MAX_TIMELY_SUBMISSION_COUNT,
  avg(rsv.LATE_SUBMISSION_COUNT) as COURSE_AVG_LATE_SUBMISSION_COUNT,
  min(rsv.LATE_SUBMISSION_COUNT) as COURSE_MIN_LATE_SUBMISSION_COUNT,
  max(rsv.LATE_SUBMISSION_COUNT) as COURSE_MAX_LATE_SUBMISSION_COUNT,
  avg(rsv.NO_SUBMISSION_COUNT) as COURSE_AVG_NO_SUBMISSION_COUNT,
  min(rsv.NO_SUBMISSION_COUNT) as COURSE_MIN_NO_SUBMISSION_COUNT,
  max(rsv.NO_SUBMISSION_COUNT) as COURSE_MAX_NO_SUBMISSION_COUNT
from
  CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_ROLLUP_BY_STUDENT_VIEW rsv
group by
  rsv.CANVAS_COURSE_ID,
  rsv.CANVAS_SECTION_ID,
  rsv.ASSIGNMENT_GROUP
)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_ROLLUP_BY_STUDENT_VIEW as
(
  select
    cgav.CANVAS_USER_ID,
    cgav.CANVAS_USER_UI_ID,
    pd.SIS_USER_ID,
    cgav.USER_NAME,
    cgav.ENROLLMENT_ID,
    cgav.CANVAS_COURSE_ID,
    cgav.COURSE_NAME,
    cgav.SCHOOL_COLLEGE,
    cgav.CANVAS_SECTION_ID,
    cgav.COURSE_SECTION_NAME,
    cgav.ASSIGNMENT_GROUP,
    sum(zeroifnull(cgav.SCORE)) as SUM_SCORE,
    sum(zeroifnull(cgav.POINTS_POSSIBLE)) as SUM_POINTS_POSSIBLE,
    avg(
      case
        when (cgav.POINTS_POSSIBLE is null or cgav.POINTS_POSSIBLE = 0)
      THEN null
      else
        (zeroifnull(cgav.SCORE)/cgav.POINTS_POSSIBLE)
      END
    ) as SCORE,
    sum(case when cgav.SUBMISSION_TIME = 'Timely' then 1 else 0 end) as TIMELY_SUBMISSION_COUNT,
    sum(case when cgav.SUBMISSION_TIME = 'Late' then 1 else 0 end) as LATE_SUBMISSION_COUNT,
    sum(case when cgav.SUBMISSION_TIME = 'Not Submitted' then 1 else 0 end) as NO_SUBMISSION_COUNT

  from
    CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_VIEW cgav
    join CANVAS_DATA_NIGHTLY_IMPORTS.PSEUDONYM_DIM pd
      on cgav.CANVAS_USER_ID = pd.USER_ID
  where
    pd.SIS_USER_ID is not null
  group by
    cgav.CANVAS_USER_ID,
    cgav.CANVAS_USER_UI_ID,
    pd.SIS_USER_ID,
    cgav.USER_NAME,
    cgav.ENROLLMENT_ID,
    cgav.CANVAS_COURSE_ID,
    cgav.COURSE_NAME,
    cgav.SCHOOL_COLLEGE,
    cgav.CANVAS_SECTION_ID,
    cgav.COURSE_SECTION_NAME,
    cgav.ASSIGNMENT_GROUP

)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_CURRENT_GRADED_ASSIGNMENT_ROLLUP_VIEW as
(
select
  cgav.CANVAS_COURSE_ID,
  cgav.COURSE_NAME,
  cgav.COURSE_SECTION_NAME,
  cgav.CANVAS_SECTION_ID,
  cgav.SCHOOL_COLLEGE,
  cgav.ASSIGNMENT_GROUP,
  cgav.ASSIGNMENT_ID,
  cgav.ASSIGNMENT_TITLE,
  max(cgav.DUE_AT) as DUE_AT,
  avg(cgav.ASSIGNMENT_SCORE) as COURSE_AVG_SCORE,
  min(cgav.ASSIGNMENT_SCORE) as COURSE_MIN_SCORE,
  max(cgav.ASSIGNMENT_SCORE) as COURSE_MAX_SCORE,
  sum(case when cgav.SUBMISSION_TIME = 'Timely' then 1 else 0 end) as TIMELY_SUBMISSION_COUNT,
  sum(case when cgav.SUBMISSION_TIME = 'Late' then 1 else 0 end) as LATE_SUBMISSION_COUNT,
  sum(case when cgav.SUBMISSION_TIME = 'Not Submitted' then 1 else 0 end) as NO_SUBMISSION_COUNT
from
  CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_VIEW cgav

group by
  cgav.CANVAS_COURSE_ID,
  cgav.COURSE_NAME,
  cgav.COURSE_SECTION_NAME,
  cgav.CANVAS_SECTION_ID,
  cgav.SCHOOL_COLLEGE,
  cgav.ASSIGNMENT_GROUP,
  cgav.ASSIGNMENT_ID,
  cgav.ASSIGNMENT_TITLE


)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_NAVIGATORS_STUDENT_CURRENT_ROLLUP_VIEW as
(
  select
    cgav.*,
    CASE
      WHEN cgav.SUBMISSION_TIME = 'Late'
        THEN DAYS_BETWEEN(cgav.SUBMITTED_AT,cgav.DUE_AT)-1  -- offsetting one day since Canvas Data is 24 hrs old
      WHEN cgav.SUBMISSION_TIME = 'Not Submitted'
        THEN DAYS_BETWEEN(now(),cgav.DUE_AT)-1  -- offsetting one day since Canvas Data is 24 hrs old
      ELSE NULL
    END as DAYS_LATE,
    carv.COURSE_AVG_SCORE,
    carv.COURSE_MIN_SCORE,
    carv.COURSE_MAX_SCORE,
    carv.TIMELY_SUBMISSION_COUNT,
    carv.LATE_SUBMISSION_COUNT,
    carv.NO_SUBMISSION_COUNT
  from
    CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_VIEW cgav
    join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_CURRENT_GRADED_ASSIGNMENT_ROLLUP_VIEW carv
      on cgav.CANVAS_SECTION_ID = carv.CANVAS_SECTION_ID and cgav.ASSIGNMENT_ID = carv.ASSIGNMENT_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_GRADED_ASSIGNMENT_VIEW as
  (select
     ceav.CANVAS_USER_ID,
     ceav.CANVAS_USER_UI_ID,
     pd.SIS_USER_ID,
     ceav.USER_NAME,
     ceav.ENROLLMENT_ID,
     ceav.CANVAS_COURSE_ID,
     ceav.COURSE_NAME,
     ceav.COURSE_CODE,
     ceav.COURSE_SECTION_NAME,
     ceav.CANVAS_SECTION_ID,
     ceav.INSTRUCTION_MODE,
     ceav.SCHOOL_COLLEGE,
     ceav.ASSIGNMENT_ID,
     ceav.ASSIGNMENT_GROUP,
     ceav.ASSIGNMENT_TITLE,
     ceav.SCORE,
     ceav.POINTS_POSSIBLE,
     case
       when ceav.POINTS_POSSIBLE is null or ceav.POINTS_POSSIBLE = 0 or ceav.score is null
        then NULL
       else cast(zeroifnull(ceav.SCORE)/ceav.POINTS_POSSIBLE as decimal(18,3))
     end as ASSIGNMENT_SCORE,
     case when ceav.SCORE is null and ceav.SUBMITTED_AT is null
        then 'Not Submitted'
       when ceav.SCORE is null and ceav.SUBMITTED_AT > ceav.DUE_AT
        then 'Submitted Late but Not Graded'
       when ceav.SCORE is null and ceav.SUBMITTED_AT is not null
        then 'Submitted but Not Graded'
       else 'Graded'
     end as GRADE_STATUS,
     ceav.DUE_AT,
     ceav.SUBMITTED_AT,
     case
       when ceav.SUBMITTED_AT > ceav.DUE_AT then 'Late'
       when ceav.SCORE is null and ceav.SUBMITTED_AT is null then 'Not Submitted'
       else 'Timely'
     end as SUBMISSION_TIME
   from
     CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW ceav
     join CANVAS_DATA_NIGHTLY_IMPORTS.CU_CANVAS_TERM_LOOKUP tlu
       on ceav.TERM_NAME = tlu.CANVAS_CURRENT_TERM_NAME
     join CANVAS_DATA_NIGHTLY_IMPORTS.PSEUDONYM_DIM pd
       on ceav.CANVAS_USER_ID = pd.USER_ID
   where
     ceav.ENROLLMENT_TYPE = 'Student'
     and ((ceav.DUE_AT <= curdate() - 1) or ceav.SCORE is not null)
     and pd.SIS_USER_ID is not null


  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_ENROLLMENTS_VIEW as
  (
    select
      *
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
      join CANVAS_DATA_NIGHTLY_IMPORTS.CU_CANVAS_TERM_LOOKUP tlu
         on cev.TERM_NAME = tlu.CANVAS_CURRENT_TERM_NAME
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_INTERACTIONS_ROLLUP_VIEW as
  (with enroll_cte as
    (
      select
        ENROLLMENT_ID,
        CANVAS_USER_ID,
        CANVAS_USER_UI_ID,
        USER_NAME,
        ENROLLMENT_TYPE,
        CANVAS_COURSE_ID,
        CANVAS_COURSE_UI_ID,
        COURSE_NAME,
        COURSE_CODE,
        COURSE_SECTION_NAME,
        INSTRUCTION_MODE,
        TERM_NAME,
        SIS_TERM,
        SCHOOL_COLLEGE

      from
        CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_CURRENT_ENROLLMENTS_VIEW ccev
      where
        CANVAS_COURSE_ID = '10430000000388220'
    )
    , current_discussions_cte as
      (
        select
          cdv.ENROLLMENT_ROLLUP_ID,
          count(*) as DISCUSSION_COUNT
        from
          enroll_cte ec
          join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_VIEW cdv
            on ec.ENROLLMENT_ID = cdv.ENROLLMENT_ROLLUP_ID
        where
          DISCUSSION_TYPE = 'Discussion'
        group by cdv.ENROLLMENT_ROLLUP_ID
      )
    , current_messages_cte as
      (
        select
          ccmv.ENROLLMENT_ID,
          count(*) as MESSAGE_COUNT
        from
          enroll_cte ec
          join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_MESSAGES_VIEW ccmv
            on ec.ENROLLMENT_ID = ccmv.ENROLLMENT_ID
        group by ccmv.ENROLLMENT_ID
      )

  select
    ec.*,
    cdc.DISCUSSION_COUNT,
    cmc.MESSAGE_COUNT,
    csf.CURRENT_SCORE
  from
    enroll_cte ec
    left join current_discussions_cte cdc
      on ec.ENROLLMENT_ID = cdc.ENROLLMENT_ROLLUP_ID
    left join current_messages_cte cmc
      on ec.ENROLLMENT_ID = cmc.ENROLLMENT_ID
    left join COURSE_SCORE_FACT csf
      on ec.ENROLLMENT_ID = csf.ENROLLMENT_ID
  )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_GROUP_MEMBERSHIP_VIEW as
(

  select
    gd.ID           as GROUP_ID,
    gd.CANVAS_ID    as GROUP_CANVAS_UI_ID,
    gd.NAME         AS GROUP_NAME,
    gd.CATEGORY     AS GROUP_CATEGORY,
    gd.CONTEXT_TYPE AS GROUP_CONTEXT_TYPE,
    gd.JOIN_LEVEL,
    gmf.PARENT_COURSE_ID,
    gmf.ENROLLMENT_TERM_ID,
    gmf.USER_ID,
    gmf.GROUP_MEMBERSHIP_ID,
    gmd.MODERATOR
  from
    GROUP_DIM gd
    join GROUP_MEMBERSHIP_FACT gmf
      on gd.ID = gmf.GROUP_ID
    join GROUP_MEMBERSHIP_DIM gmd
      on gmf.GROUP_MEMBERSHIP_ID = gmd.ID

  where
    gmd.WORKFLOW_STATE = 'accepted'
    and gd.WORKFLOW_STATE = 'available'

)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_COURSE_DISCUSSIONS_VIEW as
(
 with cte as
  (
    select
      dtd.DISCUSSION_TOPIC_ID,
      dtd.DISCUSSION_TITLE,
      dtd.DISCUSSION_TYPE,
      dtd.DISCUSSION_TOPIC_TYPE,
      dtd.CREATED_AT                                   as DISCUSSION_CREATED_AT,
      etd.NAME                                         as TERM_NAME,
      etd.SIS_SOURCE_ID                                as SIS_TERM_NAME,
      cd.NAME                                          as COURSE_NAME,
      cd.ID                                            as CANVAS_COURSE_ID,
      cd.SIS_SOURCE_ID,
      csd.NAME                                         as COURSE_SECTION_NAME,
      a.NAME                                           as SCHOOL_COLLEGE,
      dtd.GROUP_ID,
      dtd.GROUP_NAME,
      ud.ID                                            as CANVAS_USER_ID,
      ud.SORTABLE_NAME                                 as USER_NAME,
      def.DISCUSSION_ENTRY_ID,
      def.PARENT_DISCUSSION_ENTRY_ID,
      ded.WORKFLOW_STATE                               as DISCUSSION_RESPONSE_WORKFLOW,
      ded.MESSAGE                                      as DISCUSSION_RESPONSE_MESSAGE,
      convert_tz(ded.CREATED_AT, 'UTC', 'US/MOUNTAIN') as DISCUSSION_RESPONSE_CREATED_AT,
      def.ENROLLMENT_ROLLUP_ID
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_DISCUSSION_TOPIC_VIEW dtd
      join CANVAS_DATA_NIGHTLY_IMPORTS.COURSE_DIM cd
        on dtd.COURSE_ID = cd.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.ACCOUNT_DIM a
        on cd.ACCOUNT_ID = a.ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.DISCUSSION_ENTRY_FACT def
        on dtd.DISCUSSION_TOPIC_ID = def.TOPIC_ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.DISCUSSION_ENTRY_DIM ded
        on def.DISCUSSION_ENTRY_ID = ded.ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.ENROLLMENT_TERM_DIM etd
        on cd.ENROLLMENT_TERM_ID = etd.ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.USER_DIM ud
        on def.USER_ID = ud.ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ENROLLMENTS_VIEW cev
        on def.ENROLLMENT_ROLLUP_ID = cev.ENROLLMENT_ID
      left join CANVAS_DATA_NIGHTLY_IMPORTS.COURSE_SECTION_DIM csd
        on cev.CANVAS_SECTION_ID = csd.ID

  )

select DISTINCT *
from cte
where (DISCUSSION_RESPONSE_WORKFLOW is null or DISCUSSION_RESPONSE_WORKFLOW ='active')

 )
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_DISCUSSION_TOPIC_VIEW as

(
select DISTINCT
  dtf.DISCUSSION_TOPIC_ID,
  IFNULL(dtf.COURSE_ID,dtf.GROUP_PARENT_COURSE_ID) as COURSE_ID,
  dtf.GROUP_ID,
  gv.GROUP_NAME,
  IFNULL(dtf.EDITOR_ID, dtf.USER_ID) as DISCUSSION_TOPIC_EDITOR_ID,
  dtd.TITLE as DISCUSSION_TITLE,
  convert_tz(dtd.CREATED_AT, 'UTC', 'US/MOUNTAIN') as CREATED_AT,
  ifnull(dtd."TYPE", 'Discussion') as DISCUSSION_TYPE,
  dtd.DISCUSSION_TYPE as DISCUSSION_TOPIC_TYPE
from
  CANVAS_DATA_NIGHTLY_IMPORTS.DISCUSSION_TOPIC_FACT dtf
  join CANVAS_DATA_NIGHTLY_IMPORTS.DISCUSSION_TOPIC_DIM dtd
    on dtf.DISCUSSION_TOPIC_ID = dtd.ID
  left join CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_GROUP_MEMBERSHIP_VIEW gv
    on dtf.GROUP_ID = gv.GROUP_ID

where dtd.WORKFLOW_STATE = 'active'

)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_SUBMISSION_COMMENTS_VIEW as (
    select
      scd.ID as SUBMISSION_COMMENT_ID,
      scd.SUBMISSION_ID,
      scd.CANVAS_ID as CANVAS_SUBMISSION_ID,
      scd.CREATED_AT as SUBMISSION_CREATED_AT,
      scf.ASSIGNMENT_ID,
      scf.COURSE_ID,
      scd.AUTHOR_ID as SUMBISSION_COMMMENT_AUTHOR
    from
      CANVAS_DATA_NIGHTLY_IMPORTS.SUBMISSION_COMMENT_DIM scd
      join CANVAS_DATA_NIGHTLY_IMPORTS.SUBMISSION_COMMENT_FACT scf
        on scd.ID = scf.SUBMISSION_COMMENT_ID
)
/

create or replace view CANVAS_DATA_NIGHTLY_IMPORTS.CANVAS_ASSIGNMENTS_VIEW as
  (
    SELECT
      ud.id                                 as CANVAS_USER_ID,
      ud.name,
      ud.sortable_name                      as USER_NAME,
      sf.COURSE_ID,
      sf.ENROLLMENT_ROLLUP_ID,
      ad.id                                 as ASSIGNMENT_ID,
      ad.title                               as ASSIGNMENT_TITLE,
      agd.NAME                              as ASSIGNMENT_GROUP,
      sf.SCORE,
      ad.POINTS_POSSIBLE,
      ad.GRADING_TYPE,
      ad.SUBMISSION_TYPES,
      convert_tz(ad.due_at, 'UTC', 'US/MOUNTAIN') as DUE_AT,
      convert_tz(ad.PEER_REVIEWS_DUE_AT, 'UTC', 'US/MOUNTAIN') as PEER_REVIEWS_DUE_AT,
      convert_tz(sd.submitted_at, 'UTC', 'US/MOUNTAIN') as SUBMITTED_AT,
      convert_tz(sd.GRADED_AT, 'UTC', 'US/MOUNTAIN') as GRADED_AT,
      sd.attempt,
      sd.excused,
      sd.grade_state,
      sd.workflow_state,
      sd.id                                 as SUBMISSION_ID

    FROM
      CANVAS_DATA_NIGHTLY_IMPORTS.SUBMISSION_DIM sd
      JOIN CANVAS_DATA_NIGHTLY_IMPORTS.SUBMISSION_FACT sf
        on sd.ID = sf.SUBMISSION_ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.ASSIGNMENT_DIM ad
        on sf.ASSIGNMENT_ID = ad.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.ASSIGNMENT_GROUP_DIM agd
        on sf.ASSIGNMENT_GROUP_ID = agd.ID
      join CANVAS_DATA_NIGHTLY_IMPORTS.USER_DIM ud
        on ud.id = sf.USER_ID

    WHERE
      sd.WORKFLOW_STATE not in ('deleted', 'unpublished')
      and ad.WORKFLOW_STATE not in ('deleted', 'unpublished')

  )
/

create or replace view CANVAS_TERM_VIEW as
(
  select
    ID                                                                                            as TERM_ID,
    CANVAS_ID                                                                                     as CANVAS_TERM_ID,
    NAME                                                                                          as TERM_NAME,
    SIS_SOURCE_ID                                                                                 as SIS_TERM_ID,
    '20' || RIGHT(LEFT(CAST((CAST(TRIM(SIS_SOURCE_ID) as DECIMAL(18)) + 4) as varchar(4)), 3), 2) as ACADEMIC_YEAR
  from ENROLLMENT_TERM_DIM etd
  where SIS_SOURCE_ID not in ('orientation', 'migr', 'sand')
        and SIS_SOURCE_ID is not null
)
/
