-- we don't know how to generate schema CANVAS_DATA (class Schema) :(
create or replace table SCORE_FACT
(
	SCORE_ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	GRADING_PERIOD_ID DECIMAL(18),
	GRADING_PERIOD_GROUP_ID DECIMAL(18),
	GRADING_PERIOD_GROUP_ACCOUNT_ID DECIMAL(18),
	CURRENT_SCORE DECIMAL(18,3),
	FINAL_SCORE DECIMAL(18,3)
)
/

create or replace table ASSIGNMENT_OVERRIDE_USER_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_OVERRIDE_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table GROUP_FACT
(
	GROUP_ID DECIMAL(18),
	PARENT_COURSE_ID DECIMAL(18),
	PARENT_ACCOUNT_ID DECIMAL(18),
	PARENT_COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	MAX_MEMBERSHIP DECIMAL(18),
	STORAGE_QUOTA DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table SCORE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	GRADING_PERIOD_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	WORKFLOW_STATE VARCHAR(256) UTF8
)
/

create or replace table GROUP_MEMBERSHIP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	MODERATOR VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table ASSIGNMENT_OVERRIDE_FACT
(
	ASSIGNMENT_OVERRIDE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	GROUP_PARENT_ACCOUNT_ID DECIMAL(18),
	NONXLIST_COURSE_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	GROUP_WIKI_ID DECIMAL(18)
)
/

create or replace table ROLE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	BASE_ROLE_TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP
)
/

create or replace table FILE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	DISPLAY_NAME VARCHAR(500000) UTF8,
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	CONVERSATION_MESSAGE_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	FOLDER_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	REPLACEMENT_FILE_ID DECIMAL(18),
	ROOT_FILE_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	UPLOADER_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	OWNER_ENTITY_TYPE VARCHAR(256) UTF8,
	CONTENT_TYPE VARCHAR(256) UTF8,
	MD5 VARCHAR(256) UTF8,
	FILE_STATE VARCHAR(256) UTF8,
	COULD_BE_LOCKED VARCHAR(256) UTF8,
	LOCKED VARCHAR(256) UTF8,
	LOCK_AT TIMESTAMP,
	UNLOCK_AT TIMESTAMP,
	VIEWED_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP
)
/

create or replace table ASSIGNMENT_GROUP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DEFAULT_ASSIGNMENT_NAME VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table COURSE_UI_NAVIGATION_ITEM_FACT
(
	ROOT_ACCOUNT_ID DECIMAL(18),
	COURSE_UI_NAVIGATION_ITEM_ID DECIMAL(18),
	COURSE_UI_CANVAS_NAVIGATION_ID DECIMAL(18),
	EXTERNAL_TOOL_ACTIVATION_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18)
)
/

create or replace table CONVERSATION_MESSAGE_PARTICIPANT_FACT
(
	CONVERSATION_MESSAGE_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_SIZE_BYTES DECIMAL(18),
	MESSAGE_CHARACTER_COUNT DECIMAL(18),
	MESSAGE_WORD_COUNT DECIMAL(18),
	MESSAGE_LINE_COUNT DECIMAL(18)
)
/

create or replace table QUIZ_QUESTION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_QUESTION_GROUP_ID DECIMAL(18),
	FIELD_POSITION DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	ASSESSMENT_QUESTION_ID DECIMAL(18),
	ASSESSMENT_QUESTION_VERSION DECIMAL(18),
	NAME VARCHAR(4096) UTF8,
	QUESTION_TYPE VARCHAR(256) UTF8,
	QUESTION_TEXT VARCHAR(500000) UTF8,
	REGRADE_OPTION VARCHAR(256) UTF8,
	CORRECT_COMMENTS VARCHAR(500000) UTF8,
	INCORRECT_COMMENTS VARCHAR(500000) UTF8,
	NEUTRAL_COMMENTS VARCHAR(500000) UTF8
)
/

create or replace table ENROLLMENT_FACT
(
	ENROLLMENT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	COMPUTED_FINAL_SCORE DECIMAL(18,3),
	COMPUTED_CURRENT_SCORE DECIMAL(18,3)
)
/

create or replace table QUIZ_FACT
(
	QUIZ_ID DECIMAL(18),
	POINTS_POSSIBLE DECIMAL(18,3),
	TIME_LIMIT DECIMAL(18),
	ALLOWED_ATTEMPTS DECIMAL(18),
	UNPUBLISHED_QUESTION_COUNT DECIMAL(18),
	QUESTION_COUNT DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18)
)
/

create or replace table COMMUNICATION_CHANNEL_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ADDRESS VARCHAR(256) UTF8,
	TYPE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table MODULE_PREREQUISITE_FACT
(
	MODULE_PREREQUISITE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	PREREQUISITE_MODULE_ID DECIMAL(18),
	PREREQUISITE_WIKI_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table ASSIGNMENT_GROUP_FACT
(
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	GROUP_WEIGHT DECIMAL(18,3)
)
/

create or replace table WIKI_PAGE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	TITLE VARCHAR(256) UTF8,
	BODY VARCHAR(500000) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	URL VARCHAR(500000) UTF8,
	PROTECTED_EDITING BOOLEAN,
	EDITING_ROLES VARCHAR(256) UTF8,
	REVISED_AT TIMESTAMP,
	COULD_BE_LOCKED BOOLEAN
)
/

create or replace table DISCUSSION_TOPIC_FACT
(
	DISCUSSION_TOPIC_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_LENGTH DECIMAL(18),
	GROUP_ID DECIMAL(18),
	GROUP_PARENT_COURSE_ID DECIMAL(18),
	GROUP_PARENT_ACCOUNT_ID DECIMAL(18),
	GROUP_PARENT_COURSE_ACCOUNT_ID DECIMAL(18)
)
/

create or replace table ENROLLMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	ROLE_ID DECIMAL(18),
	TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	START_AT TIMESTAMP,
	END_AT TIMESTAMP,
	COMPLETED_AT TIMESTAMP,
	SELF_ENROLLED BOOLEAN,
	SIS_SOURCE_ID VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	LAST_ACTIVITY_AT TIMESTAMP
)
/

create or replace table CONVERSATION_MESSAGE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	FIELD_GENERATED BOOLEAN,
	HAS_ATTACHMENTS BOOLEAN,
	HAS_MEDIA_OBJECTS BOOLEAN,
	BODY VARCHAR(500000) UTF8
)
/

create or replace table MODULE_ITEM_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	DISCUSSION_TOPIC_ID DECIMAL(18),
	FILE_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	WIKI_PAGE_ID DECIMAL(18),
	CONTENT_TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	TITLE VARCHAR(500000) UTF8,
	URL VARCHAR(500000) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table CONFERENCE_PARTICIPANT_FACT
(
	CONFERENCE_PARTICIPANT_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	CONFERENCE_ID DECIMAL(18)
)
/

create or replace table SUBMISSION_FILE_FACT
(
	SUBMISSION_FILE_ID DECIMAL(18),
	FILE_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GRADER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18)
)
/

create or replace table QUIZ_QUESTION_GROUP_FACT
(
	QUIZ_QUESTION_GROUP_ID DECIMAL(18),
	PICK_COUNT DECIMAL(18),
	QUESTION_POINTS DECIMAL(18,3),
	QUIZ_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18)
)
/

create or replace table DISCUSSION_ENTRY_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	MESSAGE VARCHAR(500000) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	DEPTH DECIMAL(18)
)
/

create or replace table QUIZ_QUESTION_ANSWER_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	QUIZ_QUESTION_ID DECIMAL(18),
	CANVAS_DATA_TEXT VARCHAR(500000) UTF8,
	HTML VARCHAR(500000) UTF8,
	COMMENTS VARCHAR(500000) UTF8,
	TEXT_AFTER_ANSWERS VARCHAR(500000) UTF8,
	ANSWER_MATCH_LEFT VARCHAR(4096) UTF8,
	ANSWER_MATCH_RIGHT VARCHAR(4096) UTF8,
	MATCHING_ANSWER_INCORRECT_MATCHES VARCHAR(4096) UTF8,
	NUMERICAL_ANSWER_TYPE VARCHAR(256) UTF8,
	BLANK_ID VARCHAR(256) UTF8,
	EXACT DECIMAL(18,3),
	MARGIN DECIMAL(18,3),
	STARTING_RANGE DECIMAL(18,3),
	ENDING_RANGE DECIMAL(18,3)
)
/

create or replace table MODULE_FACT
(
	MODULE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table COURSE_SCORE_FACT
(
	SCORE_ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	CURRENT_SCORE DECIMAL(18,3),
	FINAL_SCORE DECIMAL(18,3),
	MUTED_CURRENT_SCORE DECIMAL(18,3),
	MUTED_FINAL_SCORE DECIMAL(18,3)
)
/

create or replace table COURSE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	CODE VARCHAR(256) UTF8,
	TYPE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	START_AT TIMESTAMP,
	CONCLUDE_AT TIMESTAMP,
	PUBLICLY_VISIBLE BOOLEAN,
	SIS_SOURCE_ID VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	WIKI_ID DECIMAL(18),
	SYLLABUS_BODY VARCHAR(500000) UTF8
)
/

create or replace table DISCUSSION_TOPIC_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	TITLE VARCHAR(256) UTF8,
	MESSAGE VARCHAR(500000) UTF8,
	TYPE VARCHAR(65535) UTF8 default NULL,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	LAST_REPLY_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELAYED_POST_AT TIMESTAMP,
	POSTED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	DISCUSSION_TYPE VARCHAR(256) UTF8,
	PINNED BOOLEAN,
	LOCKED BOOLEAN,
	COURSE_ID DECIMAL(18),
	GROUP_ID DECIMAL(18)
)
/

create or replace table ASSIGNMENT_OVERRIDE_USER_ROLLUP_FACT
(
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_OVERRIDE_ID DECIMAL(18),
	ASSIGNMENT_OVERRIDE_USER_ADHOC_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	GROUP_PARENT_ACCOUNT_ID DECIMAL(18),
	GROUP_WIKI_ID DECIMAL(18),
	NONXLIST_COURSE_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18)
)
/

create or replace table DISCUSSION_ENTRY_FACT
(
	DISCUSSION_ENTRY_ID DECIMAL(18),
	PARENT_DISCUSSION_ENTRY_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	TOPIC_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	TOPIC_USER_ID DECIMAL(18),
	TOPIC_ASSIGNMENT_ID DECIMAL(18),
	TOPIC_EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	MESSAGE_LENGTH DECIMAL(18)
)
/

create or replace table SUBMISSION_COMMENT_FACT
(
	SUBMISSION_COMMENT_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	RECIPIENT_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	MESSAGE_SIZE_BYTES DECIMAL(18),
	MESSAGE_CHARACTER_COUNT DECIMAL(18),
	MESSAGE_WORD_COUNT DECIMAL(18),
	MESSAGE_LINE_COUNT DECIMAL(18)
)
/

create or replace table GROUP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DESCRIPTION VARCHAR(500000) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	IS_PUBLIC BOOLEAN,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CONTEXT_TYPE VARCHAR(256) UTF8,
	CATEGORY VARCHAR(500000) UTF8,
	JOIN_LEVEL VARCHAR(256) UTF8,
	DEFAULT_VIEW VARCHAR(256) UTF8,
	SIS_SOURCE_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table SUBMISSION_FACT
(
	SUBMISSION_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GRADER_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	SCORE DECIMAL(18,3),
	PUBLISHED_SCORE DECIMAL(18,3),
	WHAT_IF_SCORE DECIMAL(18,3),
	SUBMISSION_COMMENTS_COUNT DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table WIKI_FACT
(
	WIKI_ID DECIMAL(18),
	PARENT_COURSE_ID DECIMAL(18),
	PARENT_GROUP_ID DECIMAL(18),
	PARENT_COURSE_ACCOUNT_ID DECIMAL(18),
	PARENT_GROUP_ACCOUNT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18)
)
/

create or replace table USER_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	TIME_ZONE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	VISIBILITY VARCHAR(256) UTF8,
	SCHOOL_NAME VARCHAR(256) UTF8,
	SCHOOL_FIELD_POSITION VARCHAR(256) UTF8,
	GENDER VARCHAR(256) UTF8,
	LOCALE VARCHAR(256) UTF8,
	PUBLIC VARCHAR(256) UTF8,
	BIRTHFIELD_DATE TIMESTAMP,
	COUNTRY_CODE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	SORTABLE_NAME VARCHAR(256) UTF8,
	GLOBAL_CANVAS_ID VARCHAR(256) UTF8
)
/

create or replace table CONFERENCE_PARTICIPANT_DIM
(
	ID DECIMAL(18),
	USER_ID DECIMAL(18),
	CONFERENCE_ID DECIMAL(18),
	PARTICIPATION_TYPE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table MODULE_PREREQUISITE_DIM
(
	ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	PREREQUISITE_MODULE_ID DECIMAL(18)
)
/

create or replace table COMMUNICATION_CHANNEL_FACT
(
	COMMUNICATION_CHANNEL_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	BOUNCE_COUNT DECIMAL(18)
)
/

create or replace table WIKI_PAGE_FACT
(
	WIKI_PAGE_ID DECIMAL(18),
	WIKI_ID DECIMAL(18),
	PARENT_COURSE_ID DECIMAL(18),
	PARENT_GROUP_ID DECIMAL(18),
	PARENT_COURSE_ACCOUNT_ID DECIMAL(18),
	PARENT_GROUP_ACCOUNT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	WIKI_PAGE_COMMENTS_COUNT DECIMAL(18),
	VIEW_COUNT DECIMAL(18)
)
/

create or replace table QUIZ_SUBMISSION_FACT
(
	SCORE DECIMAL(18,3),
	KEPT_SCORE DECIMAL(18,3),
	FIELD_DATE TIMESTAMP,
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	QUIZ_POINTS_POSSIBLE DECIMAL(18,3),
	SCORE_BEFORE_REGRADE DECIMAL(18,3),
	FUDGE_POINTS DECIMAL(18,3),
	TOTAL_ATTEMPTS DECIMAL(18),
	EXTRA_ATTEMPTS DECIMAL(18),
	EXTRA_TIME DECIMAL(18),
	TIME_TAKEN DECIMAL(18)
)
/

create or replace table COURSE_SECTION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	DEFAULT_SECTION BOOLEAN,
	ACCEPTING_ENROLLMENTS BOOLEAN,
	CAN_MANUALLY_ENROLL BOOLEAN,
	START_AT TIMESTAMP,
	END_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	RESTRICT_ENROLLMENTS_TO_SECTION_DATES BOOLEAN,
	NONXLIST_COURSE_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table REQUESTS
(
	ID VARCHAR(256) UTF8,
	FIELD_TIMESTAMP TIMESTAMP,
	TIMESTAMP_YEAR VARCHAR(256) UTF8,
	TIMESTAMP_MONTH VARCHAR(256) UTF8,
	TIMESTAMP_DAY VARCHAR(256) UTF8,
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	DISCUSSION_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	URL VARCHAR(500000) UTF8,
	USER_AGENT VARCHAR(500000) UTF8,
	HTTP_METHOD VARCHAR(256) UTF8,
	REMOTE_IP VARCHAR(256) UTF8,
	INTERACTION_MICROS DECIMAL(18),
	WEB_APPLICATION_CONTROLLER VARCHAR(256) UTF8,
	WEB_APPLICATION_ACTION VARCHAR(256) UTF8,
	WEB_APPLICATION_CONTEXT_TYPE VARCHAR(256) UTF8,
	WEB_APPLICATION_CONTEXT_ID VARCHAR(256) UTF8,
	REAL_USER_ID DECIMAL(18),
	SESSION_ID VARCHAR(256) UTF8,
	USER_AGENT_ID DECIMAL(18),
	HTTP_STATUS VARCHAR(10) UTF8,
	HTTP_VERSION VARCHAR(256) UTF8,
	DEVELOPER_KEY_ID DECIMAL(18)
)
/

create or replace table SUBMISSION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	BODY VARCHAR(500000) UTF8,
	URL VARCHAR(256) UTF8,
	GRADE VARCHAR(256) UTF8,
	SUBMITTED_AT TIMESTAMP,
	SUBMISSION_TYPE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PROCESSED BOOLEAN,
	PROCESS_ATTEMPTS DECIMAL(18),
	GRADE_MATCHES_CURRENT_SUBMISSION BOOLEAN,
	PUBLISHED_GRADE VARCHAR(256) UTF8,
	GRADED_AT TIMESTAMP,
	HAS_RUBRIC_ASSESSMENT BOOLEAN,
	ATTEMPT DECIMAL(18),
	HAS_ADMIN_COMMENT BOOLEAN,
	ASSIGNMENT_ID DECIMAL(18),
	EXCUSED VARCHAR(256) UTF8,
	GRADED_ANONYMOUSLY VARCHAR(256) UTF8,
	GRADER_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GRADE_STATE VARCHAR(256) UTF8
)
/

create or replace table GROUP_MEMBERSHIP_FACT
(
	GROUP_ID DECIMAL(18),
	PARENT_COURSE_ID DECIMAL(18),
	PARENT_ACCOUNT_ID DECIMAL(18),
	PARENT_COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	GROUP_MEMBERSHIP_ID VARCHAR(256) UTF8
)
/

create or replace table PSEUDONYM_FACT
(
	PSEUDONYM_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	LOGIN_COUNT DECIMAL(18),
	FAILED_LOGIN_COUNT DECIMAL(18)
)
/

create or replace table MODULE_COMPLETION_REQUIREMENT_DIM
(
	ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	MODULE_ITEM_ID DECIMAL(18),
	REQUIREMENT_TYPE VARCHAR(256) UTF8
)
/

create or replace table MODULE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	REQUIRE_SEQUENTIAL_PROGRESS VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	NAME VARCHAR(500000) UTF8,
	CREATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	UNLOCK_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table PSEUDONYM_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	LAST_REQUEST_AT TIMESTAMP,
	LAST_LOGIN_AT TIMESTAMP,
	CURRENT_LOGIN_AT TIMESTAMP,
	LAST_LOGIN_IP VARCHAR(256) UTF8,
	CURRENT_LOGIN_IP VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PASSWORD_AUTO_FIELD_GENERATED BOOLEAN,
	DELETED_AT TIMESTAMP,
	SIS_USER_ID VARCHAR(256) UTF8,
	UNIQUE_NAME VARCHAR(256) UTF8,
	INTEGRATION_ID VARCHAR(256) UTF8,
	AUTHENTICATION_PROVIDER_ID DECIMAL(18)
)
/

create or replace table EXTERNAL_TOOL_ACTIVATION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ACTIVATION_TARGET_TYPE VARCHAR(256) UTF8,
	URL VARCHAR(4096) UTF8,
	NAME VARCHAR(256) UTF8,
	DESCRIPTION VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	PRIVACY_LEVEL VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	TOOL_ID VARCHAR(256) UTF8,
	SELECTABLE_ALL BOOLEAN
)
/

create or replace table ASSIGNMENT_FACT
(
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	POINTS_POSSIBLE DECIMAL(18,3),
	PEER_REVIEW_COUNT DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	EXTERNAL_TOOL_ID DECIMAL(18)
)
/

create or replace table ACCOUNT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DEPTH DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	PARENT_ACCOUNT VARCHAR(256) UTF8,
	PARENT_ACCOUNT_ID DECIMAL(18),
	GRANDPARENT_ACCOUNT VARCHAR(256) UTF8,
	GRANDPARENT_ACCOUNT_ID DECIMAL(18),
	ROOT_ACCOUNT VARCHAR(256) UTF8,
	ROOT_ACCOUNT_ID DECIMAL(18),
	SUBACCOUNT1 VARCHAR(256) UTF8,
	SUBACCOUNT1_ID DECIMAL(18),
	SUBACCOUNT2 VARCHAR(256) UTF8,
	SUBACCOUNT2_ID DECIMAL(18),
	SUBACCOUNT3 VARCHAR(256) UTF8,
	SUBACCOUNT3_ID DECIMAL(18),
	SUBACCOUNT4 VARCHAR(256) UTF8,
	SUBACCOUNT4_ID DECIMAL(18),
	SUBACCOUNT5 VARCHAR(256) UTF8,
	SUBACCOUNT5_ID DECIMAL(18),
	SUBACCOUNT6 VARCHAR(256) UTF8,
	SUBACCOUNT6_ID DECIMAL(18),
	SUBACCOUNT7 VARCHAR(256) UTF8,
	SUBACCOUNT7_ID DECIMAL(18),
	SUBACCOUNT8 VARCHAR(256) UTF8,
	SUBACCOUNT8_ID DECIMAL(18),
	SUBACCOUNT9 VARCHAR(256) UTF8,
	SUBACCOUNT9_ID DECIMAL(18),
	SUBACCOUNT10 VARCHAR(256) UTF8,
	SUBACCOUNT10_ID DECIMAL(18),
	SUBACCOUNT11 VARCHAR(256) UTF8,
	SUBACCOUNT11_ID DECIMAL(18),
	SUBACCOUNT12 VARCHAR(256) UTF8,
	SUBACCOUNT12_ID DECIMAL(18),
	SUBACCOUNT13 VARCHAR(256) UTF8,
	SUBACCOUNT13_ID DECIMAL(18),
	SUBACCOUNT14 VARCHAR(256) UTF8,
	SUBACCOUNT14_ID DECIMAL(18),
	SUBACCOUNT15 VARCHAR(256) UTF8,
	SUBACCOUNT15_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table FILE_FACT
(
	FILE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	CONVERSATION_MESSAGE_AUTHOR_ID DECIMAL(18),
	CONVERSATION_MESSAGE_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	FOLDER_ID DECIMAL(18),
	GRADER_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	GROUP_CATEGORY_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_SUBMISSION_ID DECIMAL(18),
	REPLACEMENT_FILE_ID DECIMAL(18),
	ROOT_FILE_ID DECIMAL(18),
	SIS_SOURCE_ID VARCHAR(256) UTF8,
	SUBMISSION_ID DECIMAL(18),
	UPLOADER_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WIKI_ID DECIMAL(18),
	SIZE DECIMAL(18)
)
/

create or replace table CONFERENCE_FACT
(
	CONFERENCE_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	DURATION DECIMAL(18,3)
)
/

create or replace table ASSIGNMENT_OVERRIDE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_SECTION_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	ALL_DAY VARCHAR(256) UTF8,
	ALL_DAY_DATE DATE,
	ASSIGNMENT_VERSION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	DUE_AT TIMESTAMP,
	DUE_AT_OVERRIDDEN VARCHAR(256) UTF8,
	LOCK_AT TIMESTAMP,
	LOCK_AT_OVERRIDDEN VARCHAR(256) UTF8,
	SET_TYPE VARCHAR(256) UTF8,
	TITLE VARCHAR(500000) UTF8,
	UNLOCK_AT TIMESTAMP,
	UNLOCK_AT_OVERRIDDEN VARCHAR(256) UTF8,
	UPDATED_AT TIMESTAMP,
	QUIZ_VERSION DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8
)
/

create or replace table COURSE_UI_NAVIGATION_ITEM_DIM
(
	ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	VISIBLE VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18)
)
/

create or replace table COURSE_SCORE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	WORKFLOW_STATE VARCHAR(256) UTF8
)
/

create or replace table MODULE_PROGRESSION_COMPLETION_REQUIREMENT_FACT
(
	MODULE_PROGRESSION_COMPLETION_REQUIREMENT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	DISCUSSION_TOPIC_ID DECIMAL(18),
	DISCUSSION_TOPIC_EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	FILE_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	MODULE_ITEM_ID DECIMAL(18),
	MODULE_PROGRESSION_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WIKI_ID DECIMAL(18),
	WIKI_PAGE_ID DECIMAL(18),
	MIN_SCORE DECIMAL(18,3),
	SCORE DECIMAL(18,3)
)
/

create or replace table ASSIGNMENT_GROUP_RULE_DIM
(
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	DROP_LOWEST DECIMAL(18),
	DROP_HIGHEST DECIMAL(18)
)
/

create or replace table QUIZ_SUBMISSION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	QUIZ_STATE_DURING_SUBMISSION VARCHAR(256) UTF8,
	SUBMISSION_SCORING_POLICY VARCHAR(256) UTF8,
	SUBMISSION_SOURCE VARCHAR(256) UTF8,
	HAS_SEEN_RESULTS VARCHAR(256) UTF8,
	TEMPORARY_USER_CODE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	STARTED_AT TIMESTAMP,
	FINISHED_AT TIMESTAMP,
	DUE_AT TIMESTAMP
)
/

create or replace table COURSE_UI_CANVAS_NAVIGATION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	"default" VARCHAR(256) UTF8,
	ORIGINAL_FIELD_POSITION VARCHAR(256) UTF8
)
/

create or replace table QUIZ_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	POINTS_POSSIBLE DECIMAL(18,3),
	DESCRIPTION VARCHAR(500000) UTF8,
	QUIZ_TYPE VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	WORKFLOW_STATE VARCHAR(256) UTF8,
	SCORING_POLICY VARCHAR(256) UTF8,
	ANONYMOUS_SUBMISSIONS VARCHAR(256) UTF8,
	DISPLAY_QUESTIONS VARCHAR(256) UTF8,
	ANSWER_DISPLAY_ORDER VARCHAR(256) UTF8,
	GO_BACK_TO_PREVIOUS_QUESTION VARCHAR(256) UTF8,
	COULD_BE_LOCKED VARCHAR(256) UTF8,
	BROWSER_LOCKDOWN VARCHAR(256) UTF8,
	BROWSER_LOCKDOWN_FOR_DISPLAYING_RESULTS VARCHAR(256) UTF8,
	BROWSER_LOCKDOWN_MONITOR VARCHAR(256) UTF8,
	IP_FILTER VARCHAR(256) UTF8,
	SHOW_RESULTS VARCHAR(256) UTF8,
	SHOW_CORRECT_ANSWERS VARCHAR(256) UTF8,
	SHOW_CORRECT_ANSWERS_AT TIMESTAMP,
	HIDE_CORRECT_ANSWERS_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PUBLISHED_AT TIMESTAMP,
	UNLOCK_AT TIMESTAMP,
	LOCK_AT TIMESTAMP,
	DUE_AT TIMESTAMP,
	DELETED_AT TIMESTAMP
)
/

create or replace table WIKI_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	PARENT_TYPE VARCHAR(256) UTF8,
	TITLE VARCHAR(500000) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	FRONT_PAGE_URL VARCHAR(500000) UTF8,
	HAS_NO_FRONT_PAGE BOOLEAN
)
/

create or replace table QUIZ_QUESTION_FACT
(
	QUIZ_QUESTION_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	QUIZ_QUESTION_GROUP_ID DECIMAL(18),
	ASSESSMENT_QUESTION_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	POINTS_POSSIBLE DECIMAL(18,3)
)
/

create or replace table ENROLLMENT_ROLLUP_DIM
(
	ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_COUNT DECIMAL(18),
	ROLE_COUNT DECIMAL(18),
	BASE_ROLE_COUNT DECIMAL(18),
	ACCOUNT_ADMIN_ROLE_COUNT DECIMAL(18),
	TEACHER_ENROLLMENT_ROLE_COUNT DECIMAL(18),
	DESIGNER_ENROLLMENT_ROLE_COUNT DECIMAL(18),
	TA_ENROLLMENT_ROLE_COUNT DECIMAL(18),
	STUDENT_ENROLLMENT_ROLE_COUNT DECIMAL(18),
	OBSERVER_ENROLLMENT_ROLE_COUNT DECIMAL(18),
	ACCOUNT_MEMBERSHIP_ROLE_COUNT DECIMAL(18),
	NO_PERMISSIONS_ROLE_COUNT DECIMAL(18),
	ACCOUNT_ADMIN_ENROLLMENT_ID DECIMAL(18),
	TEACHER_ENROLLMENT_ENROLLMENT_ID DECIMAL(18),
	DESIGNER_ENROLLMENT_ENROLLMENT_ID DECIMAL(18),
	TA_ENROLLMENT_ENROLLMENT_ID DECIMAL(18),
	STUDENT_ENROLLMENT_ENROLLMENT_ID DECIMAL(18),
	OBSERVER_ENROLLMENT_ENROLLMENT_ID DECIMAL(18),
	ACCOUNT_MEMBERSHIP_ENROLLMENT_ID DECIMAL(18),
	NO_PERMISSIONS_ENROLLMENT_ID DECIMAL(18),
	MOST_PRIVILEGED_ROLE VARCHAR(256) UTF8,
	LEAST_PRIVILEGED_ROLE VARCHAR(256) UTF8
)
/

create or replace table ASSIGNMENT_GROUP_SCORE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	WORKFLOW_STATE VARCHAR(256) UTF8
)
/

create or replace table EXTERNAL_TOOL_ACTIVATION_FACT
(
	EXTERNAL_TOOL_ACTIVATION_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18)
)
/

create or replace table MODULE_ITEM_FACT
(
	MODULE_ITEM_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	DISCUSSION_TOPIC_ID DECIMAL(18),
	DISCUSSION_TOPIC_EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	FILE_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WIKI_ID DECIMAL(18),
	WIKI_PAGE_ID DECIMAL(18)
)
/

create or replace table ASSIGNMENT_OVERRIDE_USER_FACT
(
	ASSIGNMENT_OVERRIDE_USER_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_OVERRIDE_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18)
)
/

create or replace table SUBMISSION_COMMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	RECIPIENT_ID DECIMAL(18),
	AUTHOR_ID DECIMAL(18),
	ASSESSMENT_REQUEST_ID DECIMAL(18),
	GROUP_COMMENT_ID VARCHAR(256) UTF8,
	COMMENT VARCHAR(500000) UTF8,
	AUTHOR_NAME VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	ANONYMOUS BOOLEAN,
	TEACHER_ONLY_COMMENT BOOLEAN,
	HIDDEN BOOLEAN
)
/

create or replace table ASSIGNMENT_RULE_DIM
(
	ASSIGNMENT_ID DECIMAL(18),
	DROP_RULE VARCHAR(256) UTF8
)
/

create or replace table ASSIGNMENT_GROUP_SCORE_FACT
(
	SCORE_ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	ENROLLMENT_ID DECIMAL(18),
	CURRENT_SCORE DECIMAL(18,3),
	FINAL_SCORE DECIMAL(18,3),
	MUTED_CURRENT_SCORE DECIMAL(18,3),
	MUTED_FINAL_SCORE DECIMAL(18,3)
)
/

create or replace table MODULE_COMPLETION_REQUIREMENT_FACT
(
	MODULE_COMPLETION_REQUIREMENT_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	DISCUSSION_TOPIC_ID DECIMAL(18),
	DISCUSSION_TOPIC_EDITOR_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	FILE_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	MODULE_ITEM_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WIKI_ID DECIMAL(18),
	WIKI_PAGE_ID DECIMAL(18),
	MIN_SCORE DECIMAL(18,3)
)
/

create or replace table MODULE_PROGRESSION_COMPLETION_REQUIREMENT_DIM
(
	ID DECIMAL(18),
	MODULE_PROGRESSION_ID DECIMAL(18),
	MODULE_ITEM_ID DECIMAL(18),
	REQUIREMENT_TYPE VARCHAR(256) UTF8,
	COMPLETION_STATUS VARCHAR(256) UTF8
)
/

create or replace table ENROLLMENT_TERM_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	DATE_START TIMESTAMP,
	DATE_END TIMESTAMP,
	SIS_SOURCE_ID VARCHAR(256) UTF8
)
/

create or replace table ASSIGNMENT_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	TITLE VARCHAR(256) UTF8,
	DESCRIPTION VARCHAR(500000) UTF8,
	DUE_AT TIMESTAMP,
	UNLOCK_AT TIMESTAMP,
	LOCK_AT TIMESTAMP,
	POINTS_POSSIBLE DECIMAL(18,3),
	GRADING_TYPE VARCHAR(256) UTF8,
	SUBMISSION_TYPES VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PEER_REVIEW_COUNT DECIMAL(18),
	PEER_REVIEWS_DUE_AT TIMESTAMP,
	PEER_REVIEWS_ASSIGNED BOOLEAN,
	PEER_REVIEWS BOOLEAN,
	AUTOMATIC_PEER_REVIEWS BOOLEAN,
	ALL_DAY BOOLEAN,
	ALL_DAY_DATE DATE,
	COULD_BE_LOCKED BOOLEAN,
	GRADE_GROUP_STUDENTS_INDIVIDUALLY BOOLEAN,
	ANONYMOUS_PEER_REVIEWS BOOLEAN,
	MUTED BOOLEAN,
	ASSIGNMENT_GROUP_ID DECIMAL(18),
	FIELD_POSITION DECIMAL(18),
	VISIBILITY VARCHAR(256) UTF8,
	EXTERNAL_TOOL_ID DECIMAL(18)
)
/

create or replace table QUIZ_QUESTION_ANSWER_FACT
(
	QUIZ_QUESTION_ANSWER_ID DECIMAL(18),
	QUIZ_QUESTION_ID DECIMAL(18),
	QUIZ_QUESTION_GROUP_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	ASSESSMENT_QUESTION_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	WEIGHT DECIMAL(18,3),
	EXACT DECIMAL(18,3),
	MARGIN DECIMAL(18,3),
	STARTING_RANGE DECIMAL(18,3),
	ENDING_RANGE DECIMAL(18,3)
)
/

create or replace table CONVERSATION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	HAS_ATTACHMENTS BOOLEAN,
	HAS_MEDIA_OBJECTS BOOLEAN,
	SUBJECT VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	GROUP_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18)
)
/

create or replace table QUIZ_QUESTION_GROUP_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	NAME VARCHAR(256) UTF8,
	FIELD_POSITION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table QUIZ_SUBMISSION_HISTORICAL_FACT
(
	SCORE DECIMAL(18,3),
	KEPT_SCORE DECIMAL(18,3),
	FIELD_DATE TIMESTAMP,
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	ENROLLMENT_ROLLUP_ID DECIMAL(18),
	QUIZ_SUBMISSION_HISTORICAL_ID DECIMAL(18),
	QUIZ_POINTS_POSSIBLE DECIMAL(18,3),
	SCORE_BEFORE_REGRADE DECIMAL(18,3),
	FUDGE_POINTS DECIMAL(18,3),
	TOTAL_ATTEMPTS DECIMAL(18),
	EXTRA_ATTEMPTS DECIMAL(18),
	EXTRA_TIME DECIMAL(18),
	TIME_TAKEN DECIMAL(18)
)
/

create or replace table CONFERENCE_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	TITLE VARCHAR(256) UTF8,
	CONFERENCE_TYPE VARCHAR(256) UTF8,
	GROUP_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	START_AT TIMESTAMP,
	STARTED_AT TIMESTAMP,
	END_AT TIMESTAMP,
	ENDED_AT TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table MODULE_PROGRESSION_FACT
(
	MODULE_PROGRESSION_ID DECIMAL(18),
	ACCOUNT_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ENROLLMENT_TERM_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	WIKI_ID DECIMAL(18)
)
/

create or replace table QUIZ_SUBMISSION_HISTORICAL_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	SUBMISSION_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	VERSION_NUMBER DECIMAL(18),
	SUBMISSION_STATE VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	QUIZ_STATE_DURING_SUBMISSION VARCHAR(256) UTF8,
	SUBMISSION_SCORING_POLICY VARCHAR(256) UTF8,
	SUBMISSION_SOURCE VARCHAR(256) UTF8,
	HAS_SEEN_RESULTS VARCHAR(256) UTF8,
	TEMPORARY_USER_CODE VARCHAR(256) UTF8,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	STARTED_AT TIMESTAMP,
	FINISHED_AT TIMESTAMP,
	DUE_AT TIMESTAMP
)
/

create or replace table MODULE_PROGRESSION_DIM
(
	ID DECIMAL(18),
	CANVAS_ID DECIMAL(18),
	MODULE_ID DECIMAL(18),
	USER_ID DECIMAL(18),
	COLLAPSED VARCHAR(256) UTF8,
	IS_CURRENT VARCHAR(256) UTF8,
	WORKFLOW_STATE VARCHAR(256) UTF8,
	CURRENT_FIELD_POSITION DECIMAL(18),
	LOCK_VERSION DECIMAL(18),
	CREATED_AT TIMESTAMP,
	COMPLETED_AT TIMESTAMP,
	EVALUATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
)
/

create or replace table REQUESTS_BOTREQUESTS
(
	ID VARCHAR(256) UTF8,
	FIELD_TIMESTAMP TIMESTAMP,
	TIMESTAMP_YEAR VARCHAR(256) UTF8,
	TIMESTAMP_MONTH VARCHAR(256) UTF8,
	TIMESTAMP_DAY VARCHAR(256) UTF8,
	USER_ID DECIMAL(18),
	COURSE_ID DECIMAL(18),
	ROOT_ACCOUNT_ID DECIMAL(18),
	COURSE_ACCOUNT_ID DECIMAL(18),
	QUIZ_ID DECIMAL(18),
	DISCUSSION_ID DECIMAL(18),
	CONVERSATION_ID DECIMAL(18),
	ASSIGNMENT_ID DECIMAL(18),
	URL VARCHAR(500000) UTF8,
	USER_AGENT VARCHAR(500000) UTF8,
	HTTP_METHOD VARCHAR(256) UTF8,
	REMOTE_IP VARCHAR(256) UTF8,
	INTERACTION_MICROS DECIMAL(18),
	WEB_APPLICATION_CONTROLLER VARCHAR(256) UTF8,
	WEB_APPLICATION_ACTION VARCHAR(256) UTF8,
	WEB_APPLICATION_CONTEXT_TYPE VARCHAR(256) UTF8,
	WEB_APPLICATION_CONTEXT_ID VARCHAR(256) UTF8,
	REAL_USER_ID DECIMAL(18),
	SESSION_ID VARCHAR(256) UTF8,
	USER_AGENT_ID DECIMAL(18),
	HTTP_STATUS VARCHAR(10) UTF8,
	HTTP_VERSION VARCHAR(256) UTF8,
	DEVELOPER_KEY_ID DECIMAL(18)
)
/

create or replace table REQUESTS_USERREQUESTS
(
	FIELD_TIMESTAMP TIMESTAMP,
	TIMESTAMP_YEAR VARCHAR(256) UTF8,
	TIMESTAMP_MONTH VARCHAR(256) UTF8,
	TIMESTAMP_DAY VARCHAR(256) UTF8,
	TIMESTAMP_TIME VARCHAR(256) UTF8,
	DEVICE VARCHAR(256) UTF8,
	HTTP_METHOD VARCHAR(256) UTF8,
	HTTP_STATUS VARCHAR(256) UTF8
)
/

create or replace table REQUESTS_USER_COURSE_ROLLUPBYDAY
(
	TIMESTAMP_DAY VARCHAR(256) UTF8,
	USER_ID DECIMAL(18),
	USER_NAME VARCHAR(256) UTF8,
	TERM_NAME VARCHAR(100) UTF8,
	SIS_TERM VARCHAR(100) UTF8,
	SUB_ACCOUNT VARCHAR(256) UTF8,
	COURSE_ID DECIMAL(18),
	COURSE_NAME VARCHAR(256) UTF8,
	ENROLLMENT_TYPE VARCHAR(100) UTF8,
	CODE VARCHAR(256) UTF8,
	HTTP_METHOD VARCHAR(10) UTF8,
	COUNT_OF_REQUESTS DECIMAL(18)
)
/

create or replace view  CANVAS_DATA.CANVAS_REQUESTS_VIEW as
  (
    select
      r.FIELD_TIMESTAMP,
      r.TIMESTAMP_DAY,
      u.ID as CANVAS_USER_ID,
      u.SORTABLE_NAME,
      REPLACE(e."TYPE", 'Enrollment', '') as ENROLLMENT_TYPE,
      t.NAME                              as ENROLLMENT_TERM,
      c.NAME                              as COURSE_NAME,
      a.NAME                              as SCHOOL_COLLEGE,
      r.WEB_APPLICATION_ACTION,
      r.WEB_APPLICATION_CONTROLLER,
      r.HTTP_METHOD,
      r.HTTP_STATUS,
      r.URL,
      CASE
      WHEN r.User_agent LIKE '%Firefox/%'
        THEN 'Firefox'
      WHEN r.User_agent LIKE '%Chrome/%' OR User_agent LIKE '%CriOS%'
        THEN 'Chrome'
      WHEN r.User_agent LIKE '%MSIE %'
        THEN 'IE'
      WHEN r.User_agent LIKE '%MSIE+%'
        THEN 'IE'
      WHEN r.User_agent LIKE '%Trident%'
        THEN 'IE'
      WHEN r.User_agent LIKE '%iPhone%'
        THEN 'iPhone '
      WHEN r.User_agent LIKE '%iPad%'
        THEN 'iPad'
      WHEN r.User_agent LIKE '%Opera%'
        THEN 'Opera'
      WHEN r.User_agent LIKE '%BlackBerry%' AND User_agent LIKE '%Version/%'
        THEN 'BlackBerry WebKit'
      WHEN r.User_agent LIKE '%BlackBerry%'
        THEN 'BlackBerry'
      WHEN r.User_agent LIKE '%Android%' or User_agent LIKE '%Candroid%' OR User_agent LIKE '%candroid%'
        THEN 'Android'
      WHEN r.User_agent LIKE '%Safari%' OR User_agent LIKE '%AppleWebKit%' AND User_agent NOT LIKE '%Chrome%'
        THEN 'Safari'
      WHEN r.User_agent LIKE '%bot%'
        THEN 'Bot'
      WHEN r.User_agent LIKE '%http://%'
        THEN 'Bot'
      WHEN r.User_agent LIKE '%www.%'
        THEN 'Bot'
      WHEN r.User_agent LIKE '%Wget%'
        THEN 'Bot'
      WHEN r.User_agent LIKE '%curl%'
        THEN 'Bot'
      WHEN r.User_agent LIKE '%urllib%'
        THEN 'Bot'
      WHEN r.User_agent LIKE 'CanvasKit%' OR User_agent LIKE 'iCanvas%' OR User_agent LIKE '%icanvas%'
        THEN 'iOS/app'
      WHEN r.User_agent LIKE '%Darwin%'
        THEN 'iOS/old app'
      ELSE 'Unknown'
      END                                 AS DEVICE,
      r.USER_AGENT


    from
      CANVAS_DATA.REQUESTS r
      join CANVAS_DATA.USER_DIM u
        on r.USER_ID = u.ID
      left join ENROLLMENT_DIM e
        on r.COURSE_ID = e.COURSE_ID
      join CANVAS_DATA.COURSE_DIM c
        on e.COURSE_ID = c.ID
      join CANVAS_DATA.ACCOUNT_DIM a
        on c.ACCOUNT_ID = a.ID
      join CANVAS_DATA.ENROLLMENT_TERM_DIM t
        on c.ENROLLMENT_TERM_ID = t.ID

  )
/

create or replace view CANVAS_DATA.CANVAS_USER_REQUESTS_VIEW as
  (

    select *
    from
      CANVAS_DATA.REQUESTS_USERREQUESTS r

  )
/

create or replace view CANVAS_DATA.CANVAS_COURSE_SCORE_VIEW as
  (
    select
      cev.ENROLLMENT_ID,
      cev.TERM_NAME,
      cev.SIS_TERM,
      cev.CANVAS_USER_ID,
      cev.USER_NAME,
      cev.USER_SORTABLE_NAME,
      cev.CANVAS_COURSE_ID,
      cev.COURSE_NAME,
      cev.COURSE_CODE,
      sf.CURRENT_SCORE,
      sf.FINAL_SCORE
    from
      CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW cev
      left join CANVAS_DATA.COURSE_SCORE_FACT sf
        on cev.ENROLLMENT_ID = sf.ENROLLMENT_ID
    where
      cev.ENROLLMENT_TYPE = 'Student'

  )
/

create view CANVAS_DATA.FCQ_SCORES as
  (
    select *
    from UNIVERSITY_DATA.FCQ_SCORES
  )
/

create or replace view CANVAS_DATA.CANVAS_ASSIGNMENTS_VIEW as
  (
    SELECT
      ud.id                                 as CANVAS_USER_ID,
      ud.name,
      ud.sortable_name                      as USER_NAME,
      sf.COURSE_ID,
      sf.ENROLLMENT_ROLLUP_ID,
      ad.id                                 as ASSIGNMENT_ID,
      ad.title                               as ASSIGNMENT_TITLE,
      agd.NAME                              as ASSIGNMENT_GROUP,
      sf.SCORE,
      ad.POINTS_POSSIBLE,
      ad.GRADING_TYPE,
      ad.SUBMISSION_TYPES,
      convert_tz(ad.due_at, 'UTC', 'US/MOUNTAIN') as DUE_AT,
      convert_tz(ad.PEER_REVIEWS_DUE_AT, 'UTC', 'US/MOUNTAIN') as PEER_REVIEWS_DUE_AT,
      convert_tz(sd.submitted_at, 'UTC', 'US/MOUNTAIN') as SUBMITTED_AT,
      sd.attempt,
      sd.excused,
      sd.grade_state,
      sd.workflow_state,
      sd.id

    FROM
      CANVAS_DATA.SUBMISSION_DIM sd
      JOIN CANVAS_DATA.SUBMISSION_FACT sf
        on sd.ID = sf.SUBMISSION_ID
      join CANVAS_DATA.ASSIGNMENT_DIM ad
        on sf.ASSIGNMENT_ID = ad.ID
      join CANVAS_DATA.ASSIGNMENT_GROUP_DIM agd
        on sf.ASSIGNMENT_GROUP_ID = agd.ID
      join CANVAS_DATA.USER_DIM ud
        on ud.id = sf.USER_ID

    WHERE
      sd.WORKFLOW_STATE not in ('deleted', 'unpublished')
      and ad.WORKFLOW_STATE not in ('deleted', 'unpublished')

  )
/

create or replace view CANVAS_DATA.CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW as
  (

    select
      cev.TERM_NAME,
      cev.CANVAS_USER_ID,
      cev.USER_NAME,
      cev.USER_SORTABLE_NAME,
      cev.ENROLLMENT_ID,
      cev.CANVAS_COURSE_ID,
      cev.CANVAS_SECTION_ID,
      cev.COURSE_SECTION_NAME,
      cev.COURSE_NAME,
      cev.COURSE_CODE,
      cev.ENROLLMENT_TYPE,
      cev.SCHOOL_COLLEGE,
      cav.ASSIGNMENT_ID,
      cav.ASSIGNMENT_GROUP,
      cav.ASSIGNMENT_TITLE,
      cav.ID as SUBMISSION_ID,
      cav.SCORE,
      cav.POINTS_POSSIBLE,
      cav.DUE_AT,
      cav.SUBMITTED_AT
    from
      CANVAS_DATA.CANVAS_ASSIGNMENTS_VIEW cav
      join CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW cev
        on cev.ENROLLMENT_ID = cav.ENROLLMENT_ROLLUP_ID
  )
/

create or replace view CANVAS_COURSE_MESSAGES_VIEW as
  (
    select distinct

      cev.ENROLLMENT_ID,
      cmd.CONVERSATION_ID,
      cmpf.CONVERSATION_MESSAGE_ID,
      cev.CANVAS_USER_ID,
      cev.USER_NAME,
      cev.USER_SORTABLE_NAME,
      cev.ENROLLMENT_TYPE,
      convert_tz(cmd.CREATED_AT, 'UTC', 'US/MOUNTAIN') as CREATED_AT,
      cev.TERM_NAME,
      cev.SIS_TERM,
      cev.COURSE_NAME,
      cev.CANVAS_COURSE_ID,
      cev.SIS_SECTION_ID,
      cev.COURSE_CODE,
      cev.SCHOOL_COLLEGE
    from
      CANVAS_DATA.CONVERSATION_MESSAGE_DIM cmd
      join CANVAS_DATA.CONVERSATION_MESSAGE_PARTICIPANT_FACT cmpf
        on cmd.ID = cmpf.CONVERSATION_MESSAGE_ID and cmd.AUTHOR_ID = cmpf.USER_ID
      join CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW cev
        on cev.ENROLLMENT_ID = cmpf.ENROLLMENT_ROLLUP_ID



  )
/

create or replace  view  CANVAS_DATA.CANVAS_USER_INFO_VIEW as
  (
    select
      u.ID                    as CANVAS_USER_ID,
      psd.SIS_USER_ID         as SIS_ID,
      u.SORTABLE_NAME,
      ccd.ADDRESS             as EMAIL_ADDRESS


    from
      CANVAS_DATA.USER_DIM u
      left join CANVAS_DATA.COMMUNICATION_CHANNEL_DIM ccd
        on u.ID = ccd.USER_ID
      left join CANVAS_DATA.PSEUDONYM_DIM psd
        on u.ID = psd.USER_ID

    where
      ccd."TYPE" = 'email'
      and psd.SIS_USER_ID is not null

  )
/

create or replace view CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW as
  (

    select
      distinct
      e.ENROLLMENT_ID,
      u.ID                                 as CANVAS_USER_ID,
      u.CANVAS_ID                          as CANVAS_USER_UI_ID ,
      u.NAME                               as USER_NAME,
      u.SORTABLE_NAME                      as USER_SORTABLE_NAME,
      REPLACE(ed."TYPE", 'Enrollment', '') as ENROLLMENT_TYPE,
      ed.WORKFLOW_STATE                    as ENROLLMENT_STATE,
      convert_tz(ed.CREATED_AT, 'UTC', 'US/MOUNTAIN') as ENROLLMENT_CREATED_AT,
      convert_tz(ed.UPDATED_AT , 'UTC', 'US/MOUNTAIN') as ENROLLMENT_UPDATED_AT,
      c.ID                                 as CANVAS_COURSE_ID,
      c.CANVAS_ID                          as CANVAS_COURSE_UI_ID,
      c.NAME                               as COURSE_NAME,
      c.CODE                               as COURSE_CODE,
      csd.id                               as CANVAS_SECTION_ID,
      csd.NAME                             as COURSE_SECTION_NAME,
      case
        when LEFT(RIGHT(csd.NAME,3),1) in ('H', 'h') THEN 'Hybrid'
        when LEFT(RIGHT(csd.NAME,3),1) in ('E', 'e') THEN 'Online'
        else 'In-Person'
      end as INSTRUCTION_MODE,
      csd.SIS_SOURCE_ID                    as SIS_SECTION_ID,
      c.START_AT                           as COURSE_START,
      c.CONCLUDE_AT                        as COURSE_END,
      c.SIS_SOURCE_ID                      as SIS_COURSE_ID,
      t.NAME                               as TERM_NAME,
      t.SIS_SOURCE_ID                      as SIS_TERM,
      a.SUBACCOUNT1                        as SCHOOL_COLLEGE,
      convert_tz(ed.LAST_ACTIVITY_AT , 'UTC', 'US/MOUNTAIN')  as LAST_ACTIVITY_IN_COURSE
    from
      CANVAS_DATA.ENROLLMENT_FACT e
      join CANVAS_DATA.ENROLLMENT_DIM ed
        on e.ENROLLMENT_ID = ed.ID
      join CANVAS_DATA.USER_DIM u
        on e.USER_ID = u.ID
      left join CANVAS_DATA.PSEUDONYM_DIM p
        on u.id = p.USER_ID
      join CANVAS_DATA.COURSE_DIM c
        on e.COURSE_ID = c.ID
      join CANVAS_DATA.ENROLLMENT_TERM_DIM t
        on c.ENROLLMENT_TERM_ID = t.ID
      join CANVAS_DATA.ACCOUNT_DIM a
        on c.ACCOUNT_ID = a.ID
      join CANVAS_DATA.COURSE_SECTION_DIM csd
        on csd.ID = ed.COURSE_SECTION_ID
      join CANVAS_DATA.PSEUDONYM_DIM pd
        on ed.USER_ID = pd.USER_ID
    where
      ed.WORKFLOW_STATE not in ('rejected', 'deleted')
      and csd.WORKFLOW_STATE not in ('rejected', 'deleted')
      and c.WORKFLOW_STATE not in ('rejected', 'deleted')
      and c.SIS_SOURCE_ID is not null
      and pd.WORKFLOW_STATE = 'active'
      and local.ENROLLMENT_TYPE not in ('StudentView', 'TeacherView', 'TaView', 'Observer', 'Designer')



  )
/

create or replace view CANVAS_DATA.CANVAS_COURSE_ACTIVITY_ROLLUP_USER_VIEW as
(
 with assignment_rollup as
  (
    select
      ENROLLMENT_ID,
      count(DISTINCT ASSIGNMENT_ID)            as ASSIGNMENT_COUNT,
      count(distinct(case when SCORE is null and SUBMITTED_AT is null then null else ASSIGNMENT_ID end)) as SUBMITTED_ASSIGNMENT_COUNT  -- count if the assignment is submitted or graded
    from CANVAS_DATA.CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW

    where
      DUE_AT <= now()
    group by ENROLLMENT_ID
  )
, message_rollup as
    (
      select
        ENROLLMENT_ID,
        COUNT(1)        as MESSAGE_COUNT,
        MAX(CREATED_AT) as LAST_MESSAGE
      from
        CANVAS_DATA.CANVAS_COURSE_MESSAGES_VIEW

      group by
        ENROLLMENT_ID
    )
, discussion_rollup as
    (

      select
        ENROLLMENT_ROLLUP_ID                as ENROLLMENT_ID,
        COUNT(DISTINCT DISCUSSION_TOPIC_ID) as DISCUSSION_TOPIC_COUNT,
        count(1)                            as DISCUSSION_COUNT,
        MAX(DISCUSSION_RESPONSE_CREATED_AT)                     as LAST_DISCUSSION
      from CANVAS_DATA.CANVAS_COURSE_DISCUSSIONS_VIEW

      group by ENROLLMENT_ROLLUP_ID
    )

select
  cev.ENROLLMENT_ID,
  cev.SIS_TERM,
  cev.TERM_NAME,
  cev.CANVAS_USER_ID,
  cev.CANVAS_USER_UI_ID,
  cev.USER_NAME,
  cev.USER_SORTABLE_NAME,
  cev.ENROLLMENT_TYPE,
  cev.CANVAS_COURSE_ID,
  cev.CANVAS_COURSE_UI_ID,
  cev.COURSE_CODE,
  cev.SIS_SECTION_ID,
  cev.COURSE_NAME,
  ar.ASSIGNMENT_COUNT,
  ar.SUBMITTED_ASSIGNMENT_COUNT,
  mr.MESSAGE_COUNT,
  mr.LAST_MESSAGE,
  dr.DISCUSSION_TOPIC_COUNT,
  dr.DISCUSSION_COUNT,
  dr.LAST_DISCUSSION,
  sv.CURRENT_SCORE,
  sv.FINAL_SCORE,
  cev.LAST_ACTIVITY_IN_COURSE
from
  CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW cev
  left join assignment_rollup ar
    on cev.ENROLLMENT_ID = ar.ENROLLMENT_ID
  left join discussion_rollup dr
    on cev.ENROLLMENT_ID = dr.ENROLLMENT_ID
  left join message_rollup mr
    on cev.ENROLLMENT_ID = mr.ENROLLMENT_ID
  left join CANVAS_DATA.CANVAS_COURSE_SCORE_VIEW sv
    on cev.ENROLLMENT_ID = sv.ENROLLMENT_ID

)
/

create or replace view CANVAS_DATA.CANVAS_COURSE_DISCUSSIONS_VIEW as
(
 with cte as
  (
    select

      dtd.ID                                           as DISCUSSION_TOPIC_ID,
      CASE WHEN dtf.USER_ID is null
        then dtf.EDITOR_ID
      else dtf.USER_ID end                                DISCUSSION_EDITOR_ID,
      CASE WHEN ud2.SORTABLE_NAME is null
        then ud3.SORTABLE_NAME
      else ud2.SORTABLE_NAME end                          DISCUSSION_EDITOR_NAME,
      dtd.TITLE                                        as DISCUSSION_TITLE,
      CASE WHEN dtd."TYPE" is null
        then 'Discussion'
      ELSE dtd."TYPE" end                              as DISCUSSION_TYPE,
      convert_tz(dtd.CREATED_AT, 'UTC', 'US/MOUNTAIN') as DISCUSSION_CREATED_AT,
      etd.NAME                                         as TERM_NAME,
      etd.SIS_SOURCE_ID                                as SIS_TERM_NAME,
      cd.NAME                                          as COURSE_NAME,
      cd.ID                                            as CANVAS_COURSE_ID,
      cd.SIS_SOURCE_ID,
      a.NAME                                           as SCHOOL_COLLEGE,
      ud.ID                                            as CANVAS_USER_ID,
      ud.SORTABLE_NAME                                 as USER_NAME,
      def.DISCUSSION_ENTRY_ID,
      def.PARENT_DISCUSSION_ENTRY_ID,
      ded.WORKFLOW_STATE,
      convert_tz(ded.CREATED_AT, 'UTC', 'US/MOUNTAIN') as DISCUSSION_RESPONSE_CREATED_AT,
      def.ENROLLMENT_ROLLUP_ID

    from
      CANVAS_DATA.DISCUSSION_TOPIC_DIM dtd
      join CANVAS_DATA.DISCUSSION_TOPIC_FACT dtf
        on dtd.ID = dtf.DISCUSSION_TOPIC_ID
      join CANVAS_DATA.COURSE_DIM cd
        on dtd.COURSE_ID = cd.ID
      join CANVAS_DATA.ACCOUNT_DIM a
        on cd.ACCOUNT_ID = a.ID
      left join CANVAS_DATA.USER_DIM ud2
        on dtf.USER_ID = ud2.ID
      left join CANVAS_DATA.USER_DIM ud3
        on dtf.EDITOR_ID = ud3.ID
      left join CANVAS_DATA.DISCUSSION_ENTRY_FACT def
        on dtd.ID = def.TOPIC_ID
      left join CANVAS_DATA.DISCUSSION_ENTRY_DIM ded
        on def.DISCUSSION_ENTRY_ID = ded.ID
      left join CANVAS_DATA.ENROLLMENT_TERM_DIM etd
        on cd.ENROLLMENT_TERM_ID = etd.ID
      left join CANVAS_DATA.USER_DIM ud
        on def.USER_ID = ud.ID


    where
      dtd.WORKFLOW_STATE not in ('deleted', 'unpublished')
  )

select *
from cte
where (WORKFLOW_STATE is null or WORKFLOW_STATE ='active')

 )
/

create or replace view CANVAS_DATA.CANVAS_COURSE_ACTIVITY_ROLLUP_SECTION_VIEW as
(
 with assignment_rollup as
  (
    select
      CANVAS_COURSE_ID,
      count(distinct ASSIGNMENT_ID)         as COURSE_ASSIGNMENT_COUNT
    from

      CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW
    where
          DUE_AT <= now()
    group by CANVAS_COURSE_ID

  )
, message_rollup as
    (
      select
        CANVAS_COURSE_ID,
        COUNT(1)                            as COURSE_MESSAGE_COUNT

      from
        CANVAS_DATA.CANVAS_COURSE_MESSAGES_VIEW

      group by
        CANVAS_COURSE_ID
    )
, discussion_rollup as
    (

      select
        CANVAS_COURSE_ID,
        COUNT(DISTINCT DISCUSSION_TOPIC_ID) as DISCUSSION_TOPIC_COUNT,
        count(1)                            as COURSE_DISCUSSION_COUNT

      from CANVAS_DATA.CANVAS_COURSE_DISCUSSIONS_VIEW

      group by CANVAS_COURSE_ID
    )

select
  cev.CANVAS_COURSE_ID,
  cev.CANVAS_COURSE_UI_ID,
  cev.TERM_NAME,
  cev.SIS_TERM,
  cev.SCHOOL_COLLEGE,
  cev.COURSE_CODE,
  cev.SIS_SECTION_ID,
  cev.COURSE_SECTION_NAME,
  cev.COURSE_NAME,
  count(1)                                  as COURSE_ENROLLMENTS,
  ar.COURSE_ASSIGNMENT_COUNT,
  mr.COURSE_MESSAGE_COUNT,
  dr.DISCUSSION_TOPIC_COUNT,
  dr.COURSE_DISCUSSION_COUNT

from
  CANVAS_DATA.CANVAS_ENROLLMENTS_VIEW cev
  left join assignment_rollup ar
    on cev.CANVAS_COURSE_ID = ar.CANVAS_COURSE_ID
  left join discussion_rollup dr
    on cev.CANVAS_COURSE_ID = dr.CANVAS_COURSE_ID
  left join message_rollup mr
    on cev.CANVAS_COURSE_ID = mr.CANVAS_COURSE_ID
where
  cev.ENROLLMENT_TYPE = 'Student'
group by
  cev.CANVAS_COURSE_ID,
  cev.CANVAS_COURSE_UI_ID,
  cev.TERM_NAME,
  cev.SIS_TERM,
  cev.SCHOOL_COLLEGE,
  cev.COURSE_CODE,
  cev.SIS_SECTION_ID,
  cev.COURSE_SECTION_NAME,
  cev.COURSE_NAME,
  ar.COURSE_ASSIGNMENT_COUNT,
  mr.COURSE_MESSAGE_COUNT,
  dr.DISCUSSION_TOPIC_COUNT,
  dr.COURSE_DISCUSSION_COUNT

)
/

create or replace view CANVAS_DATA.CANVAS_UNGRADED_ASSIGNMENTS_VIEW as
  (
    select
      *
    from
      CANVAS_ENROLLED_COURSE_ASSIGNMENT_VIEW av
    where
      SCORE is null
      and DUE_AT is not null
      and SUBMITTED_AT is not null
      and ENROLLMENT_TYPE = 'Student'

  )
/
