-- we don't know how to generate schema CANVAS_LIVE_EVENTS_STG (class Schema) :(
create or replace table LOGINS
(
	LOGIN_ACTION VARCHAR(100) UTF8,
	ACTION_DATE VARCHAR(100) UTF8,
	CANVAS_USER_ID VARCHAR(255) UTF8,
	IDM_USER_ID VARCHAR(100) UTF8
)
/

create or replace table SUBMISSIONS
(
	SUBMISSION_ACTION VARCHAR(100) UTF8,
	COURSE VARCHAR(255) UTF8,
	ACTION_NAME VARCHAR(255) UTF8,
	ACTION_DATE VARCHAR(100) UTF8,
	SUBMISSION_ID VARCHAR(100) UTF8,
	CANVAS_USER_ID VARCHAR(255) UTF8
)
/
